import { Button, Dialog } from '../../../shared/components'
import type { RecipeVersion } from '../domain'
import { compareRecipeVersions } from '../services'

type Props = { open: boolean; versions: readonly RecipeVersion[]; onClose: () => void }
const currency = new Intl.NumberFormat('en-PH', { style: 'currency', currency: 'PHP' })
function formatDate(value: RecipeVersion['effectiveFrom']): string { return value ? (value instanceof Date ? value : value.toDate()).toLocaleDateString('en-PH') : 'Not effective' }

export function RecipeVersionHistoryDialog({ open, versions, onClose }: Props) { return <Dialog title="Recipe version history" open={open} onClose={onClose} footer={<Button type="button" onClick={onClose}>Close</Button>}><div className="max-h-[65vh] space-y-4 overflow-y-auto">{[...versions].sort((left, right) => right.versionNumber - left.versionNumber).map((version, index, ordered) => { const previous = ordered[index + 1]; const difference = previous ? compareRecipeVersions(previous, version) : null; return <section key={version.id} className="rounded-lg border border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">Version {version.versionNumber}</p><p className="mt-1 text-xs text-slate-500">{version.status} · Effective {formatDate(version.effectiveFrom)}</p></div><strong className="text-sm">{currency.format(version.costPerServing)} / serving</strong></div><p className="mt-3 text-sm text-slate-600">{version.changeReason}</p><dl className="mt-3 grid grid-cols-2 gap-2 text-xs text-slate-500"><div><dt>Author</dt><dd className="mt-1 font-medium text-slate-700">{version.createdBy}</dd></div><div><dt>Approver</dt><dd className="mt-1 font-medium text-slate-700">{version.approvedBy ?? 'Pending'}</dd></div></dl>{difference && <p className="mt-3 text-xs text-slate-600">Cost change: {currency.format(difference.costDifference)} · {difference.ingredientChanges.join(', ') || 'No ingredient changes'}</p>}</section> })}</div></Dialog> }
