import { describe, expect, it } from 'vitest'
import type { RecipeMaster } from '../domain'
import { cloneRecipeMaster, searchRecipeMasters, transitionRecipeMaster, validateRecipeMaster } from './recipeMasterService'

const now = new Date('2026-08-01T00:00:00.000Z')
const recipe: RecipeMaster = { id: 'r1', recipeNumber: 'REC-2026-000001', organizationId: 'org-a', productId: 'latte', productVariationId: null, recipeName: 'Cafe Latte', description: '', recipeType: 'STANDARD_PRODUCT', recipeStatus: 'DRAFT', businessVersion: '1.0', effectiveFrom: null, effectiveTo: null, ownerEmployeeId: 'owner', department: 'Head Office', workflowInstanceId: null, approvalRequired: true, published: false, publishedAt: null, publishedBy: null, retiredAt: null, retiredBy: null, cloneOfRecipeVersionId: null, notes: '', createdAt: now, createdBy: 'owner', updatedAt: now, updatedBy: 'owner' }
describe('Recipe Master', () => {
  it('validates immutable organization-unique recipe numbers', () => { expect(() => validateRecipeMaster(recipe, [])).not.toThrow(); expect(() => validateRecipeMaster({ ...recipe, id: 'r2' }, [recipe])).toThrow(); expect(() => validateRecipeMaster({ ...recipe, id: 'r2', organizationId: 'org-b' }, [recipe])).not.toThrow() })
  it('moves through controlled workflow permissions and publishes once', () => { const submitted = transitionRecipeMaster(recipe, 'PENDING_APPROVAL', 'owner', ['recipe.edit'], now).recipe; const approved = transitionRecipeMaster(submitted, 'APPROVED', 'owner', ['recipe.edit'], now).recipe; expect(() => transitionRecipeMaster(approved, 'PUBLISHED', 'owner', ['recipe.edit'], now)).toThrow('Permission denied'); const published = transitionRecipeMaster(approved, 'PUBLISHED', 'owner', ['recipe.publish'], now); expect(published.recipe.published).toBe(true); expect(published.event.type).toBe('RecipePublished'); expect(() => transitionRecipeMaster(published.recipe, 'PUBLISHED', 'owner', ['recipe.publish'], now)).toThrow() })
  it('clones without copying published state and searches master fields', () => { const clone = cloneRecipeMaster({ ...recipe, recipeStatus: 'PUBLISHED', published: true, publishedAt: now, publishedBy: 'owner' }, 'owner', 'REC-2026-000002', now); expect(clone.recipe.recipeStatus).toBe('DRAFT'); expect(clone.recipe.cloneOfRecipeVersionId).toBe(recipe.id); expect(searchRecipeMasters([recipe], 'latte')).toEqual([recipe]) })
})
