import { Archive, Pencil, Plus, Search, TriangleAlert } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Button, Card, EmptyState, Page } from '../../../shared/components'
import { IngredientEditorDialog } from '../components'
import { createLocalIngredientDraft, localIngredientCategories, localIngredients, localIngredientSuppliers, localIngredientUnits } from '../data/localIngredients'
import type { Ingredient } from '../domain'
import { createIngredientListItems } from '../services'

const currency = new Intl.NumberFormat('en-PH', { style: 'currency', currency: 'PHP' })

export function IngredientManagementPage() {
  const [ingredients, setIngredients] = useState<readonly Ingredient[]>(localIngredients)
  const [search, setSearch] = useState('')
  const [categoryId, setCategoryId] = useState('all')
  const [status, setStatus] = useState<'all' | Ingredient['status']>('all')
  const [editingIngredient, setEditingIngredient] = useState<Ingredient | null>(null)
  const rows = useMemo(() => createIngredientListItems(ingredients, localIngredientCategories, localIngredientUnits, localIngredientSuppliers).filter((row) => {
    const matchesSearch = row.ingredient.name.toLocaleLowerCase().includes(search.toLocaleLowerCase()) || row.ingredient.sku.toLocaleLowerCase().includes(search.toLocaleLowerCase())
    return matchesSearch && (categoryId === 'all' || row.ingredient.ingredientCategoryId === categoryId) && (status === 'all' || row.ingredient.status === status)
  }), [categoryId, ingredients, search, status])
  function saveIngredient(ingredient: Ingredient) { setIngredients((current) => current.some((item) => item.id === ingredient.id) ? current.map((item) => item.id === ingredient.id ? ingredient : item) : [...current, ingredient]); setEditingIngredient(null) }
  function archiveIngredient(id: string) { setIngredients((current) => current.map((ingredient) => ingredient.id === id ? { ...ingredient, status: 'archived' } : ingredient)) }
  return <Page eyebrow="Central catalog" title="Ingredients" description="Head Office standards for recipes, purchasing, costing, and future store inventory." action={<Button type="button" onClick={() => setEditingIngredient(createLocalIngredientDraft())}><Plus size={16} />Create ingredient</Button>}>
    <Card className="mb-5 p-4"><div className="grid gap-3 lg:grid-cols-[1fr_12rem_10rem]"><label className="relative"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search ingredients or SKU" className="w-full rounded-lg border border-slate-200 py-2.5 pl-9 pr-3 text-sm outline-none focus:border-emerald-600" /></label><select aria-label="Ingredient category" value={categoryId} onChange={(event) => setCategoryId(event.target.value)} className="rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-emerald-600"><option value="all">All categories</option>{localIngredientCategories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select><select aria-label="Ingredient status" value={status} onChange={(event) => setStatus(event.target.value as typeof status)} className="rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-emerald-600"><option value="all">All statuses</option><option value="active">Active</option><option value="archived">Archived</option></select></div></Card>
    {rows.length === 0 ? <EmptyState title="No ingredients found" description="Change the filters or create a centrally managed ingredient." /> : <Card className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b border-slate-200 bg-slate-50 text-xs font-bold uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Ingredient</th><th className="px-5 py-3">Category</th><th className="px-5 py-3">Base unit</th><th className="px-5 py-3">Latest cost</th><th className="px-5 py-3">Cost / unit</th><th className="px-5 py-3">Supplier</th><th className="px-5 py-3">Inventory</th><th className="px-5 py-3"><span className="sr-only">Actions</span></th></tr></thead><tbody>{rows.map((row) => <tr key={row.ingredient.id} className="border-b border-slate-100 last:border-0"><td className="px-5 py-4"><p className="font-semibold text-slate-800">{row.ingredient.name}</p><p className="mt-1 text-xs text-slate-500">{row.ingredient.status === 'archived' ? 'Archived' : row.ingredient.sku || row.ingredient.brand || 'No SKU'}</p></td><td className="px-5 py-4 text-slate-600">{row.categoryName}</td><td className="px-5 py-4 text-slate-600">{row.baseUnitSymbol}</td><td className="px-5 py-4 text-slate-600">{currency.format(row.latestPurchaseCost)}</td><td className="px-5 py-4 font-medium text-slate-700">{currency.format(row.baseUnitCost)} <span className="text-xs font-normal text-slate-500">/ {row.baseUnitSymbol}</span></td><td className="px-5 py-4 text-slate-600">{row.preferredSupplierName}</td><td className="px-5 py-4">{row.ingredient.trackInventory ? <span className="inline-flex items-center gap-1.5 text-emerald-700"><TriangleAlert size={14} />Low-stock ready</span> : <span className="text-slate-500">Not tracked</span>}</td><td className="px-5 py-4"><div className="flex justify-end gap-1"><Button aria-label={`Edit ${row.ingredient.name}`} variant="ghost" className="px-2 py-2" type="button" onClick={() => setEditingIngredient(row.ingredient)}><Pencil size={16} /></Button>{row.ingredient.status === 'active' && <Button aria-label={`Archive ${row.ingredient.name}`} variant="ghost" className="px-2 py-2 text-amber-700 hover:bg-amber-50" type="button" onClick={() => archiveIngredient(row.ingredient.id)}><Archive size={16} /></Button>}</div></td></tr>)}</tbody></table></div></Card>}
    {editingIngredient && <IngredientEditorDialog key={editingIngredient.id} ingredient={editingIngredient} categories={localIngredientCategories} units={localIngredientUnits} suppliers={localIngredientSuppliers} open onClose={() => setEditingIngredient(null)} onSave={saveIngredient} />}
  </Page>
}
