import type { CatalogProduct, MenuAvailability, ModifierGroup, PosMenuLayout, ProductCategory, ProductVariation } from '../domain'

export interface CatalogReadModel { categories: readonly ProductCategory[]; products: readonly CatalogProduct[]; variationsByProduct: Readonly<Record<string, readonly ProductVariation[]>>; optionGroups: readonly ModifierGroup[]; layout: PosMenuLayout | null; warnings: readonly string[] }
export function createCatalogReadModel(input: { branchId: string; at: Date; categories: readonly ProductCategory[]; products: readonly CatalogProduct[]; variations: readonly ProductVariation[]; optionGroups: readonly ModifierGroup[]; availability: readonly MenuAvailability[]; layouts: readonly PosMenuLayout[] }): CatalogReadModel {
  const categoryIds = new Set(input.categories.filter((category) => category.active && category.visibleOnPOS && (category.branchAvailability.length === 0 || category.branchAvailability.some((availability) => availability.branchId === input.branchId && availability.available))).sort((left, right) => left.sortOrder - right.sortOrder).map((category) => category.id))
  const unavailable = new Set(input.availability.filter((availability) => availability.branchId === input.branchId && availability.status !== 'AVAILABLE' && availability.effectiveFrom <= input.at && (availability.effectiveTo === null || input.at < availability.effectiveTo)).map((availability) => availability.productId))
  const products = input.products.filter((product) => product.active && product.visibleOnPOS && product.availableForSale && categoryIds.has(product.categoryId) && !unavailable.has(product.id))
  const variations = input.variations.filter((variation) => variation.active && products.some((product) => product.id === variation.productId) && (variation.branchAvailability.length === 0 || variation.branchAvailability.some((availability) => availability.branchId === input.branchId && availability.available)))
  const variationsByProduct = Object.fromEntries(products.map((product) => [product.id, variations.filter((variation) => variation.productId === product.id).sort((left, right) => left.sortOrder - right.sortOrder)]))
  const layout = input.layouts.find((item) => item.active && item.branchId === input.branchId) ?? input.layouts.find((item) => item.active && item.branchId === null) ?? null
  return { categories: input.categories.filter((category) => categoryIds.has(category.id)), products, variationsByProduct, optionGroups: input.optionGroups.filter((group) => group.active && (group.branchAvailability.length === 0 || group.branchAvailability.some((availability) => availability.branchId === input.branchId && availability.available))), layout, warnings: products.filter((product) => product.productType.startsWith('PREPARED') && product.recipeId === null).map((product) => `${product.name} has no recipe assignment.`) }
}
