import type { AddOn, CatalogProduct, CatalogSummary, Combo, MenuAvailability, ModifierGroup, ProductCategory, ProductPrice, ProductVariation } from '../domain'

export function validateCategory(category: ProductCategory, categories: readonly ProductCategory[]): void { if (category.parentCategoryId === category.id || (category.parentCategoryId !== null && !categories.some((item) => item.id === category.parentCategoryId))) throw new Error('Category parent is invalid.'); const visited = new Set<string>([category.id]); let parent = category.parentCategoryId; while (parent !== null) { if (visited.has(parent)) throw new Error('Category hierarchy cannot contain a cycle.'); visited.add(parent); parent = categories.find((item) => item.id === parent)?.parentCategoryId ?? null } }
export function reorderCategories(categories: readonly ProductCategory[], ids: readonly string[]): readonly ProductCategory[] { if (new Set(ids).size !== ids.length || categories.some((item) => !ids.includes(item.id))) throw new Error('Category order must include every category exactly once.'); return ids.map((id, index) => ({ ...categories.find((item) => item.id === id)!, sortOrder: index })) }
export function validateVariations(variations: readonly ProductVariation[]): void { const active = variations.filter((item) => item.active); if (active.length && active.filter((item) => item.default).length !== 1) throw new Error('Exactly one active default variation is required.'); if (variations.some((item) => item.sellingPrice < 0)) throw new Error('Variation prices cannot be negative.') }
export function resolveEffectivePrice(prices: readonly ProductPrice[], productId: string, variationId: string | null, branchId: string | null, at: Date): ProductPrice | null { const valid = prices.filter((item) => item.productId === productId && item.variationId === variationId && item.status === 'ACTIVE' && item.effectiveFrom <= at && (item.effectiveTo === null || at < item.effectiveTo) && (item.branchId === null || item.branchId === branchId)); return valid.sort((left, right) => Number(right.branchId !== null) - Number(left.branchId !== null) || right.effectiveFrom.getTime() - left.effectiveFrom.getTime())[0] ?? null }
export function validateModifierSelection(group: ModifierGroup, selectedOptionIds: readonly string[]): void { const selected = group.options.filter((option) => selectedOptionIds.includes(option.id) && option.active); if (group.selectionType === 'SINGLE' && selected.length > 1) throw new Error('Only one option may be selected.'); if (selected.length < group.minimumSelections || selected.length > group.maximumSelections || (group.required && !selected.length)) throw new Error('Modifier selection does not meet group requirements.') }
export function validateAddOn(addOn: AddOn, quantity: number, branchId: string): void { if (!addOn.active || !addOn.branchAvailability.some((item) => item.branchId === branchId && item.available)) throw new Error('Add-on is unavailable for this branch.'); if (!Number.isInteger(quantity) || quantity < 1 || (addOn.maximumQuantity !== null && quantity > addOn.maximumQuantity)) throw new Error('Add-on quantity is invalid.') }
export function calculateComboPrice(combo: Combo): number | null { const components = combo.components.reduce((sum, item) => sum + item.priceContribution * item.quantity, 0); if (combo.pricingMethod === 'PROMOTION_DRIVEN') return null; if (combo.pricingMethod === 'FIXED_PRICE') return combo.fixedPrice; if (combo.pricingMethod === 'SUM_COMPONENTS') return components; return Math.max(0, components - (combo.discountAmount ?? components * (combo.discountPercentage ?? 0))) }
export function isAvailable(availability: MenuAvailability | undefined, at: Date, branchId: string): boolean { if (!availability || availability.status === 'AVAILABLE') return true; if (availability.branchId !== null && availability.branchId !== branchId) return true; if (availability.effectiveFrom > at || (availability.effectiveTo !== null && availability.effectiveTo <= at)) return true; if (availability.dayOfWeek.length && !availability.dayOfWeek.includes(at.getDay())) return true; return false }
export function createCatalogSummary(products: readonly CatalogProduct[], branchId: string): CatalogSummary { const available = (product: CatalogProduct) => product.availableForSale && product.active && (product.status === 'ACTIVE' || product.status === 'SEASONAL'); return { activeProducts: products.filter(available).length, withoutRecipes: products.filter((item) => item.productType.startsWith('PREPARED') && item.recipeId === null).length, withoutPrices: products.filter((item) => item.baseSellingPrice === null && !item.variations.some((variation) => variation.active && variation.sellingPrice > 0)).length, hiddenFromPOS: products.filter((item) => !item.visibleOnPOS).length, unavailableAtBranch: products.filter((item) => !item.availableForSale || !item.variations.every((variation) => variation.branchAvailability.some((availability) => availability.branchId === branchId && availability.available))).length, drafts: products.filter((item) => item.status === 'DRAFT').length, needingReview: products.filter((item) => item.status === 'UNDER_REVIEW').length, recentlyUpdated: [...products].sort((a, b) => b.updatedAt.getTime() - a.updatedAt.getTime()).slice(0, 5) } }
