import { describe, expect, it } from 'vitest'
import { calculateComboPrice, reorderCategories, resolveEffectivePrice, validateModifierSelection, validateVariations } from './catalogService'

const now = new Date('2026-08-01T12:00:00.000Z')
const audit = { organizationId: 'org', createdAt: now, createdBy: 'owner', updatedAt: now, updatedBy: 'owner' }
describe('catalog service', () => {
  it('reorders complete category lists and rejects invalid variation defaults', () => { const categories = [{ ...audit, id: 'coffee', parentCategoryId: null, code: 'COF', name: 'Coffee', description: '', imageAttachmentId: null, sortOrder: 0, active: true, visibleOnPOS: true, branchAvailability: [] }, { ...audit, id: 'food', parentCategoryId: null, code: 'FOD', name: 'Food', description: '', imageAttachmentId: null, sortOrder: 1, active: true, visibleOnPOS: true, branchAvailability: [] }]; expect(reorderCategories(categories, ['food', 'coffee']).map((item) => item.id)).toEqual(['food', 'coffee']); expect(() => validateVariations([{ ...audit, id: 's', productId: 'p', code: 'S', name: 'Small', variationType: 'SIZE', sizeValue: null, sizeUnitId: null, temperature: null, recipeId: null, recipeVersionId: null, sellingPrice: 100, compareAtPrice: null, costReference: null, sku: null, barcodeIds: [], default: false, active: true, sortOrder: 0, branchAvailability: [], posLabel: 'S' }])).toThrow() })
  it('uses active branch prices and validates modifier selections', () => { const prices = [{ ...audit, id: 'standard', branchId: null, productId: 'p', variationId: null, priceType: 'STANDARD' as const, amount: 100, currencyCode: 'PHP' as const, effectiveFrom: new Date('2026-01-01'), effectiveTo: null, taxInclusive: true, status: 'ACTIVE' as const }, { ...audit, id: 'branch', branchId: 'main', productId: 'p', variationId: null, priceType: 'BRANCH' as const, amount: 110, currencyCode: 'PHP' as const, effectiveFrom: new Date('2026-01-01'), effectiveTo: null, taxInclusive: true, status: 'ACTIVE' as const }]; expect(resolveEffectivePrice(prices, 'p', null, 'main', now)?.amount).toBe(110); const group = { ...audit, id: 'milk', code: 'MILK', name: 'Milk', description: '', selectionType: 'SINGLE' as const, minimumSelections: 1, maximumSelections: 1, required: true, allowQuantity: false, active: true, sortOrder: 0, branchAvailability: [], options: [{ ...audit, id: 'fresh', modifierGroupId: 'milk', code: 'FRESH', name: 'Fresh', description: '', priceAdjustment: 0, ingredientEffects: [], recipeAdjustmentType: 'NONE' as const, active: true, sortOrder: 0, default: true, imageAttachmentId: null }] }; expect(() => validateModifierSelection(group, [])).toThrow(); expect(() => validateModifierSelection(group, ['fresh'])).not.toThrow() })
  it('calculates combo pricing without promotion logic', () => { expect(calculateComboPrice({ ...audit, id: 'combo', code: 'SET', name: 'Set', description: '', imageAttachmentId: null, pricingMethod: 'SUM_COMPONENTS_MINUS_DISCOUNT', fixedPrice: null, discountAmount: 20, discountPercentage: null, components: [{ productId: 'coffee', variationId: null, quantity: 1, required: true, allowedSubstitutionProductIds: [], priceContribution: 120 }], active: true, effectiveFrom: now, effectiveTo: null, branchAvailability: [] })).toBe(100) })
})
