import type { IngredientTimestamp } from '../../ingredients/domain'
export type ProductType = 'RAW_INGREDIENT' | 'SEMI_FINISHED_PRODUCT' | 'FINISHED_PRODUCT'
export type ProductionStatus = 'draft' | 'approved' | 'in_progress' | 'completed' | 'cancelled'
export type ProductionRecipeStatus = 'draft' | 'testing' | 'approved' | 'retired'
export type WasteReason = 'spoilage' | 'evaporation' | 'preparation_loss' | 'quality_failure' | 'operator_error' | 'other'

export interface ProductionRecipe { id: string; organizationId: string; recipeCode: string; recipeName: string; productType: ProductType; activeVersionId: string | null; status: ProductionRecipeStatus; createdAt: IngredientTimestamp; updatedAt: IngredientTimestamp; createdBy: string; updatedBy: string }
export interface ProductionRecipeInput { itemId: string; quantity: number; unitId: string; itemType: 'RAW_INGREDIENT' | 'SEMI_FINISHED_PRODUCT'; sortOrder: number }
export interface ProductionRecipeVersion { id: string; organizationId: string; productionRecipeId: string; versionNumber: number; producedItemId: string; expectedYield: number; yieldUnitId: string; shelfLifeDays: number; inputs: readonly ProductionRecipeInput[]; status: ProductionRecipeStatus; approvedBy: string | null; approvedAt: IngredientTimestamp | null; createdAt: IngredientTimestamp; createdBy: string }
export interface ProductionOrder { id: string; productionNumber: string; organizationId: string; storeId: string; productionRecipeId: string; productionRecipeVersionId: string; plannedQuantity: number; actualQuantity: number | null; expectedYield: number; wasteQuantity: number; wasteReason: WasteReason | null; wasteRecoverable: boolean; startedAt: IngredientTimestamp | null; completedAt: IngredientTimestamp | null; producedBy: string; approvedBy: string | null; shiftId: string | null; status: ProductionStatus; createdAt: IngredientTimestamp; updatedAt: IngredientTimestamp; createdBy: string; updatedBy: string }
export interface ProductionCost { consumedIngredientCost: number; packagingCost: number; utilitiesCost: number; laborCost: number; overheadCost: number; expectedCost: number; actualCost: number; variance: number; costPerOutputUnit: number }
export interface ProductionOutput { id: string; organizationId: string; storeId: string; productionOrderId: string; productionRecipeId: string; productionRecipeVersionId: string; batchId: string; quantity: number; unitId: string; totalProductionCost: number; createdAt: IngredientTimestamp; createdBy: string }
export interface ProductionWaste { id: string; organizationId: string; storeId: string; productionOrderId: string; quantity: number; unitId: string; reason: WasteReason; recoverable: boolean; recordedAt: IngredientTimestamp; recordedBy: string }
export interface ProductionBatch { id: string; batchNumber: string; organizationId: string; storeId: string; productionOrderId: string; productionRecipeId: string; productionRecipeVersionId: string; productionDate: IngredientTimestamp; expiryDate: IngredientTimestamp; originalQuantity: number; remainingQuantity: number; unitId: string; totalProductionCost: number; unitCost: number; producedBy: string; shiftId: string | null; createdAt: IngredientTimestamp; updatedAt: IngredientTimestamp; createdBy: string; updatedBy: string }
