import type { IngredientTimestamp } from '../../ingredients/domain'
export type CurrencyCode = 'PHP'
export type AccountType = 'ASSET' | 'LIABILITY' | 'EQUITY' | 'REVENUE' | 'COST_OF_SALES' | 'EXPENSE'
export interface FinancialAudit { organizationId: string; branchId: string | null; businessUnitId?: string | null; currencyCode: CurrencyCode; createdAt: IngredientTimestamp; createdBy: string; updatedAt: IngredientTimestamp; updatedBy: string; sourceDocumentType?: string; sourceDocumentId?: string }
export interface ChartAccount extends FinancialAudit { id: string; code: string; name: string; description?: string; accountType: AccountType; accountSubtype: string; parentAccountId: string | null; normalBalance: 'DEBIT' | 'CREDIT'; allowManualPosting: boolean; systemAccount: boolean; active: boolean; branchRestricted: boolean }
export interface FinancialAccount extends FinancialAudit { id: string; code: string; name: string; category: 'CASH' | 'BANK' | 'PETTY_CASH' | 'DIGITAL_WALLET' | 'CLEARING'; linkedChartAccountId: string; openingBalance: number; openingBalanceDate: IngredientTimestamp; currentOperationalBalance: number; allowNegativeBalance: boolean; reconciliationRequired: boolean; active: boolean; confidential: boolean }
export interface SupplierInvoice extends FinancialAudit { id: string; invoiceNumber: string; supplierInvoiceNumber: string; supplierId: string; purchaseOrderId?: string; goodsReceiptIds: readonly string[]; invoiceDate: IngredientTimestamp; receivedDate: IngredientTimestamp; dueDate: IngredientTimestamp; subtotal: number; discountAmount: number; taxAmount: number; shippingAmount: number; otherCharges: number; totalAmount: number; paidAmount: number; outstandingAmount: number; status: 'DRAFT' | 'PENDING_APPROVAL' | 'APPROVED' | 'POSTED' | 'PARTIALLY_PAID' | 'PAID' | 'DISPUTED' | 'CANCELLED' | 'VOIDED'; approvalStatus: 'NOT_REQUIRED' | 'PENDING' | 'APPROVED' | 'REJECTED'; notes?: string }
export interface AccountsPayable extends FinancialAudit { id: string; supplierId: string; supplierInvoiceId: string; invoiceDate: IngredientTimestamp; dueDate: IngredientTimestamp; originalAmount: number; paidAmount: number; creditApplied: number; outstandingAmount: number; status: 'OPEN' | 'PARTIALLY_PAID' | 'PAID' | 'DISPUTED' | 'VOIDED'; lastPaymentDate?: IngredientTimestamp; closedAt?: IngredientTimestamp }
export interface SupplierPayment extends FinancialAudit { id: string; paymentNumber: string; supplierId: string; paymentDate: IngredientTimestamp; financialAccountId: string; paymentMethod: string; paymentAmount: number; referenceNumber?: string; status: 'DRAFT' | 'PENDING_APPROVAL' | 'APPROVED' | 'POSTED' | 'REVERSED' | 'CANCELLED' | 'VOIDED'; approvalStatus: 'NOT_REQUIRED' | 'PENDING' | 'APPROVED' | 'REJECTED'; notes?: string }
export interface SupplierPaymentAllocation { id: string; supplierPaymentId: string; supplierInvoiceId: string; allocatedAmount: number; discountTaken: number; withholdingAmount: number; appliedAt: IngredientTimestamp }
export interface Expense extends FinancialAudit { id: string; expenseNumber: string; expenseDate: IngredientTimestamp; supplierId?: string; categoryId: string; expenseAccountId: string; description: string; subtotal: number; taxAmount: number; totalAmount: number; paymentStatus: 'UNPAID' | 'PARTIALLY_PAID' | 'PAID'; expenseStatus: 'DRAFT' | 'PENDING_APPROVAL' | 'APPROVED' | 'POSTED' | 'REJECTED' | 'CANCELLED' | 'VOIDED'; approvalStatus: 'NOT_REQUIRED' | 'PENDING' | 'APPROVED' | 'REJECTED'; financialAccountId?: string }
export interface ExpenseCategory { id: string; organizationId: string; code: string; name: string; defaultExpenseAccountId: string; requiresSupplier: boolean; requiresReceipt: boolean; requiresApproval: boolean; active: boolean; sortOrder: number }
export interface CashTransfer extends FinancialAudit { id: string; transferNumber: string; transferDate: IngredientTimestamp; sourceFinancialAccountId: string; destinationFinancialAccountId: string; amount: number; transferFee: number; transferFeeAccountId?: string; status: 'DRAFT' | 'PENDING_APPROVAL' | 'APPROVED' | 'COMPLETED' | 'REVERSED' | 'CANCELLED'; approvalStatus: 'NOT_REQUIRED' | 'PENDING' | 'APPROVED' | 'REJECTED'; notes?: string }
export interface AccountingPeriod { id: string; organizationId: string; fiscalYear: number; periodNumber: number; name: string; startDate: IngredientTimestamp; endDate: IngredientTimestamp; status: 'OPEN' | 'SOFT_CLOSED' | 'CLOSED'; closedAt?: IngredientTimestamp; closedBy?: string }
export interface JournalEntry extends FinancialAudit { id: string; journalNumber: string; postingDate: IngredientTimestamp; accountingPeriodId: string; description: string; status: 'DRAFT' | 'PENDING_APPROVAL' | 'APPROVED' | 'POSTED' | 'REVERSED' | 'VOIDED'; totalDebit: number; totalCredit: number; reversalOfEntryId?: string }
export interface JournalLine { id: string; journalEntryId: string; accountId: string; branchId: string | null; description: string; debitAmount: number; creditAmount: number }
export type TaxType = 'GST' | 'VAT' | 'SALES_TAX' | 'ZERO_RATED' | 'EXEMPT' | 'NO_TAX' | 'OTHER'
export type TaxCalculationMode = 'TAX_INCLUSIVE' | 'TAX_EXCLUSIVE' | 'NOT_APPLICABLE'
export type TaxPriceDisplayMode = 'SHOW_INCLUSIVE' | 'SHOW_EXCLUSIVE' | 'SHOW_BOTH'
export type TaxRoundingMethod = 'HALF_UP' | 'HALF_EVEN' | 'DOWN' | 'UP'
export interface TaxProfileVersion { id: string; taxProfileId: string; rate: string; calculationMode: TaxCalculationMode; effectiveFrom: Date; effectiveTo: Date | null; active: boolean; roundingMethod: TaxRoundingMethod; roundingPrecision: number; createdAt: IngredientTimestamp; createdBy: string; changeReason: string }
export interface TaxProfile { id: string; organizationId: string; code: string; name: string; description: string | null; taxType: TaxType; priceDisplayMode: TaxPriceDisplayMode; taxPayableAccountId: string | null; taxExpenseAccountId: string | null; recoverableTaxAccountId: string | null; branchIds: readonly string[] | null; priority: number; active: boolean; versions: readonly TaxProfileVersion[]; createdAt: IngredientTimestamp; createdBy: string; updatedAt: IngredientTimestamp; updatedBy: string }
export interface TaxResolutionContext { organizationId: string; branchId: string; transactionAt: Date; explicitTaxProfileId?: string; productTaxProfileId?: string; categoryTaxProfileId?: string; branchDefaultTaxProfileId?: string; organizationDefaultTaxProfileId?: string }
export interface TaxSnapshot { taxProfileId: string | null; taxConfigurationVersionId: string | null; taxCode: string; taxName: string; taxType: TaxType; rateApplied: string; calculationMode: TaxCalculationMode; taxableAmountMinor: number; taxAmountMinor: number; taxInclusiveAmountMinor: number; taxExclusiveAmountMinor: number; zeroRatedAmountMinor: number; exemptAmountMinor: number; roundingAdjustmentMinor: number; calculatedAt: Date }
