export const APP_CONFIG = {
  name: 'Accaza Business Platform',
  locale: 'en-PH',
  currency: 'PHP',
  version: '2.0.0',
} as const

export const ROUTES = {
  catalog: '/catalog',
  catalogCategories: '/catalog/categories',
  catalogProducts: '/catalog/products',
  catalogOptionGroups: '/catalog/option-groups',
  catalogOptionItems: '/catalog/option-items',
  catalogVariations: '/catalog/variations',
  settings: '/settings',
  businessSetup: '/setup',
  dashboard: '/',
  pos: '/pos',
  menuManagement: '/menu-management',
  masterData: '/master-data',
  ingredients: '/ingredients',
  recipeStudio: '/recipes',
  operations: '/operations',
  procurement: '/procurement',
  production: '/production',
  platformConfiguration: '/platform-configuration',
  finance: '/finance',
  taxConfiguration: '/finance/tax-configuration',
  interBranchTransfers: '/inter-branch-transfers',
  crm: '/crm',
  analytics: '/analytics',
  workflow: '/workflow',
  assets: '/assets',
  hr: '/hr',
  franchise: '/franchise',
} as const
