import type { IngredientTimestamp } from '../../ingredients/domain'
export type InterBranchTransferStatus = 'DRAFT' | 'SUBMITTED' | 'PENDING_APPROVAL' | 'APPROVED' | 'REJECTED' | 'PREPARING' | 'PARTIALLY_DISPATCHED' | 'DISPATCHED' | 'IN_TRANSIT' | 'PARTIALLY_RECEIVED' | 'RECEIVED' | 'COMPLETED' | 'CANCELLED' | 'DISPUTED' | 'REVERSED'
export type InterBranchTransferType = 'BRANCH_TO_BRANCH' | 'WAREHOUSE_TO_BRANCH' | 'BRANCH_TO_WAREHOUSE' | 'COMMISSARY_TO_BRANCH' | 'BRANCH_RETURN' | 'EMERGENCY_TRANSFER' | 'FRANCHISE_SUPPLY'
export interface InterBranchTransfer { id: string; transferNumber: string; organizationId: string; sourceOrganizationId: string; destinationOrganizationId: string; sourceBranchId: string; destinationBranchId: string; sourceLocationId: string; destinationLocationId: string; transferType: InterBranchTransferType; status: InterBranchTransferStatus; priority: 'NORMAL' | 'HIGH' | 'URGENT'; requestedDate: IngredientTimestamp; requestedBy: string; approvedBy: string | null; dispatchDate: IngredientTimestamp | null; actualArrivalDate: IngredientTimestamp | null; completedDate: IngredientTimestamp | null; reason: string; notes?: string; trackingReference?: string; transferCostAmount: number; currencyCode: 'PHP'; attachmentIds: readonly string[]; createdAt: IngredientTimestamp; createdBy: string; updatedAt: IngredientTimestamp; updatedBy: string }
export interface TransferBatchAllocation { sourceBatchId: string; sourceBatchNumber: string; quantity: number; unitCost: number; expiryDate: IngredientTimestamp | null }
export interface InterBranchTransferLine { id: string; transferId: string; itemId: string; ingredientId?: string; requestedQuantity: number; approvedQuantity: number; preparedQuantity: number; dispatchedQuantity: number; receivedQuantity: number; acceptedQuantity: number; rejectedQuantity: number; damagedQuantity: number; missingQuantity: number; unit: string; sourceBatchAllocations: readonly TransferBatchAllocation[]; destinationBatchIds: readonly string[]; lineStatus: 'REQUESTED' | 'APPROVED' | 'PREPARED' | 'DISPATCHED' | 'PARTIALLY_RECEIVED' | 'RECEIVED' | 'DISCREPANCY' | 'CANCELLED'; notes?: string }
export interface TransferShipment { id: string; shipmentNumber: string; transferId: string; organizationId: string; sourceBranchId: string; destinationBranchId: string; dispatchDate: IngredientTimestamp; shipmentStatus: 'DRAFT' | 'READY' | 'DISPATCHED' | 'IN_TRANSIT' | 'PARTIALLY_RECEIVED' | 'RECEIVED' | 'DELAYED' | 'LOST' | 'CANCELLED'; carrierType: 'INTERNAL_DELIVERY' | 'THIRD_PARTY_COURIER' | 'PICKUP' | 'OTHER'; trackingReference?: string; preparedBy: string; dispatchedBy: string; receivedBy: string | null; createdAt: IngredientTimestamp; updatedAt: IngredientTimestamp }
export interface TransferDiscrepancy { id: string; transferId: string; shipmentId: string; transferLineId: string; discrepancyType: 'MISSING' | 'DAMAGED' | 'EXCESS' | 'WRONG_ITEM' | 'WRONG_BATCH' | 'EXPIRED' | 'QUALITY_FAILURE' | 'TEMPERATURE_BREACH' | 'DOCUMENTATION_ERROR' | 'OTHER'; expectedQuantity: number; actualQuantity: number; varianceQuantity: number; unit: string; description: string; reportedBy: string; reportedAt: IngredientTimestamp; responsibility: 'SOURCE_BRANCH' | 'DESTINATION_BRANCH' | 'CARRIER' | 'SUPPLIER' | 'UNKNOWN'; resolutionStatus: 'OPEN' | 'UNDER_REVIEW' | 'APPROVED' | 'RESOLVED' | 'REJECTED' }
export interface DestinationTransferBatch { id: string; organizationId: string; branchId: string; locationId: string; itemId: string; sourceTransferId: string; sourceShipmentId: string; sourceBatchId: string; originalSourceBatchNumber: string; receivedQuantity: number; remainingQuantity: number; unit: string; unitCost: number; totalCost: number; expiryDate: IngredientTimestamp | null; receivedAt: IngredientTimestamp; receivedBy: string; batchStatus: 'AVAILABLE' | 'QUARANTINED' }
