export type ProductType = 'PREPARED_BEVERAGE' | 'PREPARED_FOOD' | 'PACKAGED_PRODUCT' | 'MERCHANDISE' | 'SEMI_FINISHED_PRODUCT' | 'FINISHED_INVENTORY_PRODUCT' | 'SERVICE' | 'COMBO' | 'GIFT_CARD' | 'OTHER'
export type ProductStatus = 'DRAFT' | 'UNDER_REVIEW' | 'ACTIVE' | 'SEASONAL' | 'TEMPORARILY_UNAVAILABLE' | 'RETIRED' | 'ARCHIVED'
export type PreparationType = 'MADE_TO_ORDER' | 'PREMADE' | 'MANUFACTURED' | 'REPACKAGED' | 'NO_PREPARATION'
export type VariationType = 'SIZE' | 'TEMPERATURE' | 'FLAVOR' | 'PACKAGE' | 'PREPARATION' | 'CUSTOM'
export type Temperature = 'HOT' | 'ICED' | 'WARM' | 'ROOM_TEMPERATURE' | 'FROZEN' | 'NOT_APPLICABLE'
export type PriceType = 'STANDARD' | 'BRANCH' | 'FUTURE' | 'RECOMMENDED' | 'HEAD_OFFICE_FIXED' | 'WHOLESALE' | 'CUSTOM'
export type AvailabilityStatus = 'AVAILABLE' | 'TEMPORARILY_UNAVAILABLE' | 'SOLD_OUT' | 'SCHEDULED' | 'SEASONAL' | 'DISCONTINUED'
export type SelectionType = 'SINGLE' | 'MULTIPLE'
export type RecipeAdjustmentType = 'NONE' | 'ADD_INGREDIENT' | 'REMOVE_INGREDIENT' | 'SUBSTITUTE_INGREDIENT' | 'INCREASE_QUANTITY' | 'REDUCE_QUANTITY' | 'REPLACE_RECIPE_COMPONENT' | 'CUSTOM'
export interface CatalogAudit { organizationId: string; createdAt: Date; createdBy: string; updatedAt: Date; updatedBy: string }
export interface BranchAvailability { branchId: string; available: boolean }
export interface ProductCategory extends CatalogAudit { id: string; parentCategoryId: string | null; code: string; name: string; description: string; imageAttachmentId: string | null; sortOrder: number; active: boolean; visibleOnPOS: boolean; branchAvailability: readonly BranchAvailability[] }
export interface ProductVariation extends CatalogAudit { id: string; productId: string; code: string; name: string; variationType: VariationType; sizeValue: number | null; sizeUnitId: string | null; temperature: Temperature | null; recipeId: string | null; recipeVersionId: string | null; sellingPrice: number; compareAtPrice: number | null; costReference: number | null; sku: string | null; barcodeIds: readonly string[]; default: boolean; active: boolean; sortOrder: number; branchAvailability: readonly BranchAvailability[]; posLabel: string }
export interface CatalogProduct extends CatalogAudit { id: string; productCode: string; name: string; shortName: string | null; description: string; categoryId: string; brandId: string | null; productType: ProductType; preparationType: PreparationType; taxProfileId: string | null; baseSellingPrice: number | null; currencyCode: 'PHP'; sku: string | null; barcodeIds: readonly string[]; imageAttachmentIds: readonly string[]; primaryImageAttachmentId: string | null; recipeId: string | null; currentRecipeVersionId: string | null; trackInventoryDirectly: boolean; allowModifiers: boolean; allowAddOns: boolean; allowNotes: boolean; availableForSale: boolean; visibleOnPOS: boolean; availableOnline: boolean; active: boolean; status: ProductStatus; tags: readonly string[]; variations: readonly ProductVariation[] }
export interface ProductPrice extends CatalogAudit { id: string; branchId: string | null; productId: string; variationId: string | null; priceType: PriceType; amount: number; currencyCode: 'PHP'; effectiveFrom: Date; effectiveTo: Date | null; taxInclusive: boolean; status: 'ACTIVE' | 'RETIRED' }
export interface ModifierIngredientEffect { ingredientId: string; quantity: number; unitId: string; action: RecipeAdjustmentType; replacementIngredientId: string | null }
export interface ModifierOption extends CatalogAudit { id: string; modifierGroupId: string; code: string; name: string; description: string; priceAdjustment: number; ingredientEffects: readonly ModifierIngredientEffect[]; recipeAdjustmentType: RecipeAdjustmentType; active: boolean; sortOrder: number; default: boolean; imageAttachmentId: string | null }
export interface ModifierGroup extends CatalogAudit { id: string; code: string; name: string; description: string; selectionType: SelectionType; minimumSelections: number; maximumSelections: number; required: boolean; allowQuantity: boolean; active: boolean; sortOrder: number; branchAvailability: readonly BranchAvailability[]; options: readonly ModifierOption[] }
export interface AddOn extends CatalogAudit { id: string; code: string; name: string; categoryId: string | null; sellingPrice: number; currencyCode: 'PHP'; ingredientRequirements: readonly ModifierIngredientEffect[]; recipeId: string | null; maximumQuantity: number | null; active: boolean; branchAvailability: readonly BranchAvailability[]; imageAttachmentId: string | null; taxProfileId: string | null; sortOrder: number }
export interface ComboComponent { productId: string; variationId: string | null; quantity: number; required: boolean; allowedSubstitutionProductIds: readonly string[]; priceContribution: number }
export interface Combo extends CatalogAudit { id: string; code: string; name: string; description: string; imageAttachmentId: string | null; pricingMethod: 'FIXED_PRICE' | 'SUM_COMPONENTS' | 'SUM_COMPONENTS_MINUS_DISCOUNT' | 'PROMOTION_DRIVEN'; fixedPrice: number | null; discountAmount: number | null; discountPercentage: number | null; components: readonly ComboComponent[]; active: boolean; effectiveFrom: Date; effectiveTo: Date | null; branchAvailability: readonly BranchAvailability[] }
export interface MenuAvailability extends CatalogAudit { id: string; branchId: string | null; productId: string; status: AvailabilityStatus; dayOfWeek: readonly number[]; startsAt: string | null; endsAt: string | null; effectiveFrom: Date; effectiveTo: Date | null; reason: string | null }
export interface PosMenuLayout extends CatalogAudit { id: string; branchId: string | null; name: string; layoutType: 'ORGANIZATION_DEFAULT' | 'BRANCH'; categoryOrder: readonly string[]; productOrder: readonly string[]; featuredProductIds: readonly string[]; quickAccessProductIds: readonly string[]; active: boolean }
export interface CatalogSummary { activeProducts: number; withoutRecipes: number; withoutPrices: number; hiddenFromPOS: number; unavailableAtBranch: number; drafts: number; needingReview: number; recentlyUpdated: readonly CatalogProduct[] }
