import { CheckCircle2, ChevronLeft, ChevronRight, RotateCcw, ShieldCheck } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Button, Card, Page } from '../../../shared/components'
import { APP_CONFIG, ROUTES } from '../../../shared/config'
import { FEATURE_REGISTRY } from '../../platform-configuration/services'
import type { BusinessSetupDraft } from '../domain'
import { buildSetupPlan, createLocalBusinessSetupRepository, validateSetupDraft } from '../services'

const steps = ['Welcome', 'Business profile', 'Organization', 'Branch', 'Taxes', 'Units', 'Categories', 'Chart of accounts', 'Payment methods', 'Features', 'Owner account', 'Review', 'Initialize', 'Success']
const days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
const storageKey = 'abp.business-setup.draft'
const defaultFeatures = (Object.keys(FEATURE_REGISTRY) as (keyof typeof FEATURE_REGISTRY)[]).filter((key) => FEATURE_REGISTRY[key].defaultEnabled && key !== 'FRANCHISE.ENABLED')
function initialDraft(): BusinessSetupDraft { return { idempotencyKey: crypto.randomUUID().replaceAll('-', ''), step: 1, status: 'in_progress', profile: { legalName: '', tradeName: '', businessType: 'coffee_shop', logoUrl: '', address: '', country: '', province: '', city: '', postalCode: '', timezone: Intl.DateTimeFormat().resolvedOptions().timeZone || 'Asia/Manila', currency: 'PHP', language: 'en', fiscalYearStartMonth: 1, businessDays: days }, organizationName: '', branch: { code: '', name: '', address: '', openingHours: '', managerName: '', timezone: Intl.DateTimeFormat().resolvedOptions().timeZone || 'Asia/Manila', currency: 'PHP' }, tax: { name: '', rate: '', mode: 'exclusive' }, chartTemplate: 'coffee_shop', enabledFeatures: defaultFeatures, owner: { name: '', email: '', password: '' }, updatedAt: new Date().toISOString() } }
function restoreDraft(): BusinessSetupDraft { try { const stored = window.localStorage.getItem(storageKey); if (!stored) return initialDraft(); const parsed = JSON.parse(stored) as BusinessSetupDraft; return { ...initialDraft(), ...parsed, owner: { ...initialDraft().owner, ...parsed.owner, password: '' }, status: parsed.status === 'initialized' ? 'initialized' : 'in_progress' } } catch { return initialDraft() } }
function Input({ label, value, onChange, type = 'text' }: { label: string; value: string | number; onChange: (value: string) => void; type?: 'text' | 'email' | 'password' | 'number' }) { return <label className="block text-sm font-medium text-slate-700">{label}<input type={type} value={value} onChange={(event) => onChange(event.target.value)} className="mt-1.5 w-full rounded-lg border border-slate-200 px-3 py-2.5 outline-none focus:border-emerald-600" /></label> }

export function BusinessSetupPage() {
  const navigate = useNavigate(); const [draft, setDraft] = useState<BusinessSetupDraft>(restoreDraft); const [error, setError] = useState(''); const [initializing, setInitializing] = useState(false); const [initialized, setInitialized] = useState(draft.status === 'initialized')
  useEffect(() => { const { owner, ...safe } = draft; window.localStorage.setItem(storageKey, JSON.stringify({ ...safe, owner: { ...owner, password: '' } })) }, [draft])
  const plan = useMemo(() => { try { return buildSetupPlan(draft) } catch { return null } }, [draft])
  const update = (changes: Partial<BusinessSetupDraft>) => setDraft((current) => ({ ...current, ...changes, updatedAt: new Date().toISOString() }))
  const next = () => { try { if (draft.step === 2 || draft.step === 4 || draft.step === 5 || draft.step === 11 || draft.step === 12) validateSetupDraft({ ...draft, step: 14, status: 'in_progress' }); setError(''); update({ step: Math.min(14, draft.step + 1) }) } catch (reason) { setError(reason instanceof Error ? 'Complete the required fields before continuing.' : 'Complete the required fields before continuing.') } }
  const previous = () => { setError(''); update({ step: Math.max(1, draft.step - 1) }) }
  const cancel = () => { update({ status: 'cancelled' }); navigate(ROUTES.dashboard) }
  const restart = async () => { await createLocalBusinessSetupRepository().rollback(draft.idempotencyKey); window.localStorage.removeItem(storageKey); const fresh = initialDraft(); setDraft(fresh); setInitialized(false); setError('') }
  const initialize = async () => { try { setInitializing(true); const setupPlan = buildSetupPlan({ ...draft, step: 14 }); const repository = createLocalBusinessSetupRepository(); const existing = await repository.getByKey(draft.idempotencyKey); await repository.initialize(existing ?? setupPlan); update({ status: 'initialized', step: 14 }); setInitialized(true); setError('') } catch { setError('Initialization could not be completed. Your setup draft is preserved so you can retry safely.') } finally { setInitializing(false) } }
  const body = (() => {
    if (initialized || draft.step === 14) return <div className="space-y-5 text-center"><CheckCircle2 className="mx-auto text-emerald-600" size={48} /><div><h2 className="text-2xl font-semibold">Business successfully configured</h2><p className="mt-2 text-sm text-slate-600">Your setup plan is saved locally and can be applied by the trusted setup service when Firebase commands are enabled.</p></div><div className="grid gap-2 sm:grid-cols-2"><Button onClick={() => navigate(ROUTES.dashboard)}>Go to dashboard</Button><Button variant="secondary" onClick={() => navigate(ROUTES.settings)}>Open settings</Button><Button variant="secondary" onClick={() => navigate(ROUTES.menuManagement)}>Import products</Button><Button variant="secondary" onClick={() => navigate(ROUTES.recipeStudio)}>Import recipes</Button><Button variant="secondary" onClick={() => navigate(ROUTES.ingredients)}>Import inventory</Button><Button variant="secondary" onClick={() => navigate(ROUTES.finance)}>Configure finance</Button><Button variant="secondary" onClick={() => navigate(ROUTES.hr)}>Invite employees</Button></div></div>
    if (draft.step === 1) return <div className="space-y-4"><h2 className="text-2xl font-semibold">Welcome to {APP_CONFIG.name}</h2><p className="text-slate-600">Version {APP_CONFIG.version}. This guided setup creates a single-store foundation that can grow into multiple company-owned branches and franchises.</p><div className="rounded-lg bg-slate-50 p-4 text-sm"><strong>Configuration status:</strong> {draft.status === 'in_progress' ? 'Draft in progress' : 'Not started'}</div></div>
    if (draft.step === 2) return <div className="grid gap-4 sm:grid-cols-2"><Input label="Business name" value={draft.profile.legalName} onChange={(legalName) => update({ profile: { ...draft.profile, legalName } })} /><Input label="Trade name" value={draft.profile.tradeName} onChange={(tradeName) => update({ profile: { ...draft.profile, tradeName } })} /><label className="text-sm font-medium">Business type<select value={draft.profile.businessType} onChange={(event) => update({ profile: { ...draft.profile, businessType: event.target.value as BusinessSetupDraft['profile']['businessType'] } })} className="mt-1.5 w-full rounded-lg border p-2.5">{['coffee_shop', 'restaurant', 'bakery', 'cafe', 'retail', 'other'].map((type) => <option key={type}>{type.replaceAll('_', ' ')}</option>)}</select></label><Input label="Logo URL (optional)" value={draft.profile.logoUrl} onChange={(logoUrl) => update({ profile: { ...draft.profile, logoUrl } })} /><Input label="Business address" value={draft.profile.address} onChange={(address) => update({ profile: { ...draft.profile, address } })} /><Input label="Country" value={draft.profile.country} onChange={(country) => update({ profile: { ...draft.profile, country } })} /><Input label="Province" value={draft.profile.province} onChange={(province) => update({ profile: { ...draft.profile, province } })} /><Input label="City" value={draft.profile.city} onChange={(city) => update({ profile: { ...draft.profile, city } })} /><Input label="Postal code" value={draft.profile.postalCode} onChange={(postalCode) => update({ profile: { ...draft.profile, postalCode } })} /><Input label="Timezone" value={draft.profile.timezone} onChange={(timezone) => update({ profile: { ...draft.profile, timezone } })} /><Input label="Language" value={draft.profile.language} onChange={(language) => update({ profile: { ...draft.profile, language } })} /><Input label="Fiscal-year start month" type="number" value={draft.profile.fiscalYearStartMonth} onChange={(value) => update({ profile: { ...draft.profile, fiscalYearStartMonth: Number(value) } })} /><p className="text-sm text-slate-600 sm:col-span-2">Currency: PHP · Business days: {draft.profile.businessDays.join(', ')}</p></div>
    if (draft.step === 3) return <div className="space-y-4"><h2 className="text-xl font-semibold">Head Office organization</h2><Input label="Organization name" value={draft.organizationName} onChange={(organizationName) => update({ organizationName })} /><p className="text-sm text-slate-600">This is the default company-owned organization. Future franchises remain separate organizations.</p></div>
    if (draft.step === 4) return <div className="grid gap-4 sm:grid-cols-2"><Input label="Branch code" value={draft.branch.code} onChange={(code) => update({ branch: { ...draft.branch, code: code.toUpperCase() } })} /><Input label="Branch name" value={draft.branch.name} onChange={(name) => update({ branch: { ...draft.branch, name } })} /><Input label="Branch address" value={draft.branch.address} onChange={(address) => update({ branch: { ...draft.branch, address } })} /><Input label="Opening hours" value={draft.branch.openingHours} onChange={(openingHours) => update({ branch: { ...draft.branch, openingHours } })} /><Input label="Manager" value={draft.branch.managerName} onChange={(managerName) => update({ branch: { ...draft.branch, managerName } })} /><Input label="Branch timezone" value={draft.branch.timezone} onChange={(timezone) => update({ branch: { ...draft.branch, timezone } })} /></div>
    if (draft.step === 5) return <div className="grid gap-4 sm:grid-cols-3"><Input label="Tax name" value={draft.tax.name} onChange={(name) => update({ tax: { ...draft.tax, name } })} /><Input label="Rate (controlled decimal, 0 to 1)" type="text" value={draft.tax.rate} onChange={(rate) => update({ tax: { ...draft.tax, rate } })} /><label className="text-sm font-medium">Tax mode<select value={draft.tax.mode} onChange={(event) => update({ tax: { ...draft.tax, mode: event.target.value as BusinessSetupDraft['tax']['mode'] } })} className="mt-1.5 w-full rounded-lg border p-2.5"><option value="exclusive">Tax exclusive</option><option value="inclusive">Tax inclusive</option><option value="exempt">Tax exempt</option></select></label></div>
    if (draft.step === 6) return <Seed title="Standard units" items={['grams', 'kilograms', 'ml', 'liters', 'pieces', 'boxes', 'packs', 'cups', 'ounces', 'shots', 'tablespoons', 'teaspoons']} />
    if (draft.step === 7) return <Seed title="Master categories" items={['Ingredient Categories', 'Product Categories', 'Expense Categories', 'Supplier Categories', 'Asset Categories', 'Customer Categories']} />
    if (draft.step === 8) return <div><h2 className="text-xl font-semibold">Chart of accounts</h2><p className="mt-2 text-sm text-slate-600">Use the existing default coffee-shop chart or prepare an import for review.</p><label className="mt-4 block text-sm font-medium"><select value={draft.chartTemplate} onChange={(event) => update({ chartTemplate: event.target.value as BusinessSetupDraft['chartTemplate'] })} className="mt-1.5 w-full rounded-lg border p-2.5"><option value="coffee_shop">Default coffee shop chart</option><option value="import_existing">Import existing chart</option></select></label></div>
    if (draft.step === 9) return <Seed title="Payment methods" items={['Cash', 'GCash', 'Maya', 'Bank Transfer', 'Credit Card', 'Debit Card', 'Gift Card', 'Store Credit', 'Loyalty Redemption']} />
    if (draft.step === 10) return <div className="space-y-2">{(Object.keys(FEATURE_REGISTRY) as (keyof typeof FEATURE_REGISTRY)[]).map((key) => <label key={key} className="flex items-center justify-between rounded-lg border p-3 text-sm"><span>{FEATURE_REGISTRY[key].name}</span><input type="checkbox" disabled={key === 'FRANCHISE.ENABLED'} checked={draft.enabledFeatures.includes(key)} onChange={(event) => update({ enabledFeatures: event.target.checked ? [...draft.enabledFeatures, key] : draft.enabledFeatures.filter((value) => value !== key) })} /></label>)}<p className="text-xs text-slate-500">Franchise remains disabled by default.</p></div>
    if (draft.step === 11) return <div className="grid gap-4 sm:grid-cols-2"><Input label="Owner name" value={draft.owner.name} onChange={(name) => update({ owner: { ...draft.owner, name } })} /><Input label="Owner email" type="email" value={draft.owner.email} onChange={(email) => update({ owner: { ...draft.owner, email } })} /><div className="sm:col-span-2"><Input label="Owner password" type="password" value={draft.owner.password} onChange={(password) => update({ owner: { ...draft.owner, password } })} /></div><p className="text-xs text-slate-500 sm:col-span-2">Passwords are never saved in the resumable browser draft.</p></div>
    if (draft.step === 12) return <div className="space-y-3 text-sm"><h2 className="text-xl font-semibold">Review setup</h2><p><strong>Business:</strong> {draft.profile.legalName || 'Not completed'}</p><p><strong>Organization:</strong> {draft.organizationName || 'Not completed'}</p><p><strong>First branch:</strong> {draft.branch.name || 'Not completed'}</p><p><strong>Owner:</strong> {draft.owner.email || 'Not completed'}</p><p><strong>Features:</strong> {draft.enabledFeatures.length}</p></div>
    return <div className="space-y-4"><ShieldCheck className="text-emerald-700" size={36} /><h2 className="text-xl font-semibold">Initialize business setup</h2><p className="text-sm text-slate-600">This creates an idempotent setup plan for the organization, first branch, master data, chart, payment methods, roles, feature flags, dashboards, and audit record. It never overwrites an existing plan.</p><Button disabled={!plan || initializing} onClick={() => void initialize()}>{initializing ? 'Initializing…' : 'Initialize business'}</Button></div>
  })()
  return <Page eyebrow="Initial configuration" title="Business setup wizard" description="Configure your business without technical setup."><div className="grid gap-5 lg:grid-cols-[14rem_1fr]"><Card className="p-4"><ol className="space-y-1">{steps.map((label, index) => <li key={label} className={`rounded px-2 py-1.5 text-xs ${draft.step === index + 1 ? 'bg-emerald-50 font-semibold text-emerald-800' : 'text-slate-500'}`}>{index + 1}. {label}</li>)}</ol></Card><Card className="p-6"><div className="mb-6 flex items-center justify-between text-xs text-slate-500"><span>Step {draft.step} of 14</span><div className="flex gap-2"><Button variant="secondary" className="px-2 py-1 text-xs" onClick={cancel}>Cancel</Button><Button variant="secondary" className="px-2 py-1 text-xs" onClick={() => void restart()}><RotateCcw size={14} />Restart</Button></div></div>{body}{error && <p role="alert" className="mt-5 rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}{!initialized && <footer className="mt-8 flex justify-between border-t pt-5"><Button variant="secondary" disabled={draft.step === 1} onClick={previous}><ChevronLeft size={16} />Back</Button>{draft.step < 13 ? <Button onClick={next}>Continue<ChevronRight size={16} /></Button> : <span />}</footer>}</Card></div></Page>
}
function Seed({ title, items }: { title: string; items: readonly string[] }) { return <div><h2 className="text-xl font-semibold">{title}</h2><p className="mt-2 text-sm text-slate-600">These operational defaults can be extended later without rewriting setup.</p><div className="mt-4 flex flex-wrap gap-2">{items.map((item) => <span key={item} className="rounded-full bg-slate-100 px-3 py-1 text-sm text-slate-700">{item}</span>)}</div></div> }
