export type AvailabilityReason = 'AVAILABLE' | 'INACTIVE' | 'BRANCH_UNAVAILABLE' | 'SOLD_OUT' | 'SCHEDULED' | 'SEASONAL' | 'COMING_SOON' | 'DISCONTINUED' | 'OUTSIDE_HOURS'
export interface BranchAvailability { branchId: string; available: boolean }
export interface CategoryDocument { id: string; organizationId: string; code: string; name: string; parentCategoryId?: string | null; sortOrder: number; active: boolean; visibleOnPOS: boolean; branchAvailability?: readonly BranchAvailability[] }
export interface ProductDocument { id: string; organizationId: string; productCode: string; name: string; shortName?: string | null; productType: string; categoryId: string; active: boolean; status: string; availableForSale: boolean; visibleOnPOS: boolean; baseSellingPrice?: number | null; taxProfileId?: string | null; recipeId?: string | null; currentRecipeVersionId?: string | null; primaryImageAttachmentId?: string | null; sku?: string | null; barcodeIds?: readonly string[]; posLabel?: string | null; branchAvailability?: readonly BranchAvailability[]; effectiveFrom?: Date | null; effectiveTo?: Date | null }
export interface VariationDocument { id: string; organizationId: string; productId: string; code: string; name: string; variationType: string; sizeValue?: number | null; sizeUnitId?: string | null; temperature?: string | null; sku?: string | null; barcodeIds?: readonly string[]; posLabel?: string | null; sellingPrice?: number | null; recipeId?: string | null; recipeVersionId?: string | null; default?: boolean; active: boolean; branchAvailability?: readonly BranchAvailability[]; effectiveFrom?: Date | null; effectiveTo?: Date | null }
export interface OptionGroupDocument { id: string; organizationId: string; code: string; name: string; selectionType: 'SINGLE' | 'MULTIPLE'; minimumSelections: number; maximumSelections: number; required: boolean; active: boolean; branchAvailability?: readonly BranchAvailability[] }
export interface IngredientEffect { ingredientId: string; quantity: number; unitId: string; action: 'ADD_INGREDIENT' | 'REMOVE_INGREDIENT' | 'SUBSTITUTE_INGREDIENT' | 'INCREASE_QUANTITY' | 'REDUCE_QUANTITY' | 'REPLACE_RECIPE_COMPONENT'; replacementIngredientId?: string | null; multiplier?: number }
export interface OptionItemDocument { id: string; organizationId: string; modifierGroupId: string; code: string; name: string; priceAdjustment: number; taxProfileId?: string | null; recipeAdjustmentType: IngredientEffect['action'] | 'NONE'; ingredientEffects: readonly IngredientEffect[]; active: boolean; maximumQuantity?: number | null; branchAvailability?: readonly BranchAvailability[] }
export interface ProductOptionAssignmentDocument { id: string; organizationId: string; productId?: string | null; variationId?: string | null; optionGroupId: string; requiredOverride?: boolean | null; minimumOverride?: number | null; maximumOverride?: number | null; sortOrder: number; active: boolean; branchAvailability?: readonly BranchAvailability[] }
export interface AvailabilityDocument { id: string; organizationId: string; branchId?: string | null; productId?: string | null; variationId?: string | null; optionItemId?: string | null; status: string; dayOfWeek?: readonly number[]; startsAt?: string | null; endsAt?: string | null; effectiveFrom?: Date | null; effectiveTo?: Date | null; timezone?: string | null }
export interface CategorySnapshot { categoryId: string; categoryCode: string; categoryName: string; parentCategoryId?: string; sortOrder: number; visibleOnPOS: boolean }
export interface ProductSnapshot { productId: string; productCode: string; productName: string; shortName?: string; productType: string; categoryId: string; categoryCode: string; categoryName: string; imageReference?: string; sku?: string; barcode?: string; posLabel: string; currentStatus: string }
export interface VariationSnapshot { variationId: string; variationCode: string; variationName: string; variationType: string; sizeValue?: number; sizeUnitId?: string; temperature?: string; sku?: string; barcode?: string; posLabel: string }
export interface OptionSnapshot { optionGroupId: string; optionGroupCode: string; optionGroupName: string; optionItemId: string; optionItemCode: string; optionItemName: string; quantity: number; unitPriceAdjustment: number; taxProfileId?: string; recipeAdjustmentType: string; ingredientEffectsSnapshot: readonly IngredientEffect[] }
export interface AvailabilityResult { available: boolean; reason: AvailabilityReason; evaluatedAt: Date }
