import type { IngredientTimestamp } from '../../ingredients/domain'
export type InventoryOperatingMode = 'SIMPLE_STORAGE' | 'ADVANCED_WAREHOUSE'
export type FeatureKey = 'PLATFORM.MULTI_BRANCH' | 'INVENTORY.SIMPLE_STORAGE' | 'INVENTORY.ADVANCED_WAREHOUSE' | 'INVENTORY.LOCATION_TRACKING' | 'INVENTORY.BATCH_STATUS' | 'INVENTORY.INTERNAL_TRANSFERS' | 'INVENTORY.RESERVATIONS' | 'INVENTORY.BARCODE_SCANNING' | 'INVENTORY.PICK_LISTS' | 'INVENTORY.DIRECTED_PUTAWAY' | 'MANUFACTURING.ENABLED' | 'FINANCE.ENABLED' | 'FINANCE.ACCOUNTS_PAYABLE' | 'FINANCE.SUPPLIER_INVOICES' | 'FINANCE.SUPPLIER_PAYMENTS' | 'FINANCE.EXPENSES' | 'FINANCE.CASH_ACCOUNTS' | 'FINANCE.BANK_ACCOUNTS' | 'FINANCE.PETTY_CASH' | 'FINANCE.APPROVALS' | 'FINANCE.CHART_OF_ACCOUNTS' | 'FINANCE.JOURNALS' | 'FINANCE.PERIODS' | 'FINANCE.POS_SETTLEMENTS' | 'FINANCE.BRANCH_REPORTING' | 'FINANCE.CONSOLIDATED_REPORTING' | 'CRM.ENABLED' | 'LOYALTY.ENABLED' | 'FRANCHISE.ENABLED'
export type FeatureStatus = 'ACTIVE' | 'PREVIEW' | 'PLANNED' | 'DEPRECATED'
export interface FeatureDefinition { key: FeatureKey; name: string; description: string; category: string; defaultEnabled: boolean; configurableAtOrganization: boolean; configurableAtBranch: boolean; dependencies: readonly FeatureKey[]; conflicts: readonly FeatureKey[]; minimumRoleToConfigure: 'owner' | 'head_office_admin'; status: FeatureStatus; createdAt: IngredientTimestamp; updatedAt: IngredientTimestamp }
export interface FeatureConfiguration { id: string; organizationId: string; branchId: string | null; featureKey: FeatureKey; enabled: boolean; configuration?: Readonly<Record<string, string | number | boolean>>; configuredBy: string; configuredAt: IngredientTimestamp; reason?: string }
export type StorageLocationType = 'MAIN_STORAGE' | 'DRY_STORAGE' | 'CHILLER' | 'FREEZER' | 'BAR' | 'PRODUCTION' | 'RECEIVING' | 'WASTE_HOLDING' | 'WAREHOUSE' | 'ZONE' | 'AISLE' | 'RACK' | 'SHELF' | 'BIN' | 'OTHER'
export type TemperatureClass = 'AMBIENT' | 'CHILLED' | 'FROZEN' | 'CONTROLLED' | 'NOT_APPLICABLE'
export interface StorageLocation { id: string; organizationId: string; branchId: string; code: string; name: string; description?: string; locationType: StorageLocationType; parentLocationId: string | null; hierarchyPath: string; hierarchyLevel: number; isDefault: boolean; isActive: boolean; allowsInventory: boolean; allowsReceiving: boolean; allowsProductionOutput: boolean; allowsWaste: boolean; temperatureClass?: TemperatureClass; sortOrder: number; createdAt: IngredientTimestamp; createdBy: string; updatedAt: IngredientTimestamp; updatedBy: string }
export type InventoryTransferStatus = 'DRAFT' | 'COMPLETED' | 'REVERSED' | 'CANCELLED'
export interface InventoryTransfer { id: string; transferNumber: string; organizationId: string; branchId: string; batchId: string; itemId: string; fromLocationId: string; toLocationId: string; quantity: number; unit: string; status: InventoryTransferStatus; reason: string; notes?: string; requestedBy: string; completedBy: string | null; requestedAt: IngredientTimestamp; completedAt: IngredientTimestamp | null; reversedBy: string | null; reversedAt: IngredientTimestamp | null }
export interface InventoryLocationMovement { id: string; organizationId: string; branchId: string; batchId: string; itemId: string; movementType: 'RECEIPT_PUTAWAY' | 'INTERNAL_TRANSFER' | 'PRODUCTION_ISSUE' | 'PRODUCTION_OUTPUT' | 'WASTE_MOVE' | 'RETURN_MOVE' | 'ADJUSTMENT' | 'REVERSAL'; sourceDocumentType: string; sourceDocumentId: string; fromLocationId: string | null; toLocationId: string | null; quantity: number; unit: string; performedBy: string; performedAt: IngredientTimestamp; reversalOf: string | null; metadata?: Readonly<Record<string, string>> }
export interface InventoryReservation { id: string; organizationId: string; branchId: string; itemId: string; batchId: string | null; locationId: string | null; quantity: number; unit: string; reservationType: 'PRODUCTION' | 'TRANSFER' | 'SALES_ORDER' | 'MANUAL'; sourceDocumentType: string; sourceDocumentId: string; status: 'ACTIVE' | 'PARTIALLY_CONSUMED' | 'CONSUMED' | 'RELEASED' | 'EXPIRED' | 'CANCELLED'; reservedBy: string; reservedAt: IngredientTimestamp; expiresAt: IngredientTimestamp | null; releasedAt: IngredientTimestamp | null }
