import type { IngredientTimestamp } from '../../ingredients/domain'
export interface Customer { id: string; customerNumber: string; organizationId: string; homeBranchId: string | null; preferredBranchId: string | null; membershipId: string | null; firstName: string; middleName: string; lastName: string; displayName: string; mobileNumber: string; email: string; birthDate: IngredientTimestamp | null; marketingConsent: boolean; smsConsent: boolean; emailConsent: boolean; status: 'ACTIVE' | 'INACTIVE' | 'BLACKLISTED' | 'MERGED' | 'DELETED'; mergedIntoCustomerId: string | null; createdAt: IngredientTimestamp; updatedAt: IngredientTimestamp; createdBy: string; updatedBy: string }
export interface MembershipTier { id: string; organizationId: string; name: string; minimumSpend: number; minimumVisits: number; minimumPoints: number; active: boolean; sortOrder: number }
export interface LoyaltyAccount { id: string; organizationId: string; customerId: string; availablePoints: number; lifetimePoints: number; updatedAt: IngredientTimestamp }
export interface LoyaltyTransaction { id: string; customerId: string; saleId: string | null; branchId: string | null; type: 'EARN' | 'REDEEM' | 'ADJUSTMENT' | 'EXPIRATION' | 'PROMOTION_BONUS' | 'BIRTHDAY_BONUS' | 'REVERSAL'; points: number; balanceAfter: number; reason: string; performedBy: string; performedAt: IngredientTimestamp }
export interface Reward { id: string; organizationId: string; rewardCode: string; name: string; pointsRequired: number; active: boolean; validFrom: IngredientTimestamp; validUntil: IngredientTimestamp | null }
export interface Promotion { id: string; organizationId: string; name: string; type: 'PERCENTAGE' | 'FIXED' | 'BUNDLE' | 'COUPON' | 'MEMBERSHIP' | 'MANUAL'; priority: number; stackable: boolean; startAt: IngredientTimestamp; endAt: IngredientTimestamp; minimumSpend: number; maximumDiscount: number | null; active: boolean }
export interface Coupon { id: string; organizationId: string; code: string; promotionId: string; active: boolean; singleUse: boolean; usedCount: number; usageLimit: number | null; expiresAt: IngredientTimestamp | null }
export interface GiftCard { id: string; organizationId: string; code: string; balance: number; status: 'ISSUED' | 'ACTIVE' | 'SUSPENDED' | 'EXPIRED'; expiresAt: IngredientTimestamp | null }
