import type { IngredientTimestamp } from '../../ingredients/domain'
export type PaymentTerms = 'cash' | 'cod' | 'net_7' | 'net_15' | 'net_30' | 'net_45' | 'net_60' | 'custom'
export type PurchaseMethod = 'purchase_order' | 'direct' | 'online'
export type PurchaseOrderStatus = 'draft' | 'submitted' | 'approved' | 'partially_received' | 'received' | 'cancelled'
export type InventoryBatchStatus = 'available' | 'depleted' | 'expired' | 'quarantined'
export type ControlledBatchStatus = 'AVAILABLE' | 'RESERVED' | 'IN_PRODUCTION' | 'QUARANTINED' | 'EXPIRED' | 'DAMAGED' | 'DISPOSED' | 'RETURNED_TO_SUPPLIER' | 'DEPLETED'
export interface Supplier { id: string; organizationId: string; supplierCode: string; companyName: string; contactPerson: string; phone: string; email: string; address: string; taxId: string; paymentTerms: PaymentTerms; customPaymentTerms: string; creditLimit: number; leadTimeDays: number; active: boolean; notes: string; createdAt: IngredientTimestamp; updatedAt: IngredientTimestamp; createdBy: string; updatedBy: string }
export interface PurchaseLine { id: string; ingredientId: string; ingredientNameSnapshot: string; orderedQuantity: number; unitId: string; unitCost: number; discount: number; taxRate: number; lineTotal: number }
export interface PurchaseOrder { id: string; organizationId: string; storeId: string; poNumber: string; supplierId: string | null; method: PurchaseMethod; onlinePlatform: 'shopee' | 'lazada' | 'other' | null; onlineOrderNumber: string; trackingNumber: string; status: PurchaseOrderStatus; orderDate: IngredientTimestamp; expectedDelivery: IngredientTimestamp | null; currency: string; paymentTerms: PaymentTerms; lines: readonly PurchaseLine[]; supplierInvoiceNumber: string; createdAt: IngredientTimestamp; updatedAt: IngredientTimestamp; createdBy: string; updatedBy: string }
export interface GoodsReceiptLine { purchaseLineId: string; ingredientId: string; actualQuantity: number; acceptedQuantity: number; rejectedQuantity: number; damagedQuantity: number; batchNumber: string; expiryDate: IngredientTimestamp | null; receivedUnitCost: number; notes: string }
export interface GoodsReceipt { id: string; organizationId: string; storeId: string; purchaseOrderId: string | null; supplierId: string | null; method: PurchaseMethod; receivedAt: IngredientTimestamp; supplierInvoiceNumber: string; notes: string; lines: readonly GoodsReceiptLine[]; createdBy: string }
export interface InventoryBatch { id: string; organizationId: string; storeId: string; batchNumber: string; ingredientId: string; supplierId: string | null; purchaseReference: string; receivedDate: IngredientTimestamp; expiryDate: IngredientTimestamp | null; originalQuantity: number; remainingQuantity: number; unitId: string; unitCost: number; status: InventoryBatchStatus; batchStatus?: ControlledBatchStatus; currentLocationId?: string; currentLocationPath?: string; locationAssignedAt?: IngredientTimestamp; locationAssignedBy?: string; createdAt: IngredientTimestamp; updatedAt: IngredientTimestamp; createdBy: string; updatedBy: string }
export interface ProcurementDocument { id: string; organizationId: string; storeId: string; purchaseReference: string; type: 'invoice' | 'delivery_receipt' | 'official_receipt' | 'photo' | 'quotation' | 'purchase_order_pdf'; storagePath: string; fileName: string; createdAt: IngredientTimestamp; createdBy: string }
export interface FifoConsumption { batchId: string; ingredientId: string; quantity: number; unitCost: number; cost: number }
export interface FifoResult { consumptions: readonly FifoConsumption[]; totalCost: number; updatedBatches: readonly InventoryBatch[] }
