import { describe, expect, it } from 'vitest'
import type { IngredientCategory, IngredientMaster } from '../domain'
import { createIngredientMasterService, validateIngredientCategory, validateIngredientMaster } from './ingredientService'

const now = new Date('2026-08-01T00:00:00.000Z')
const category: IngredientCategory = { id: 'beans', organizationId: 'org-a', parentCategoryId: null, code: 'INGCAT-BEANS', name: 'Beans', description: '', sortOrder: 0, active: true, inventoryTracked: true, edible: true, perishable: false, defaultShelfLifeDays: null, defaultStorageClass: 'DRY', createdAt: now, createdBy: 'owner', updatedAt: now, updatedBy: 'owner' }
const ingredient: IngredientMaster = { id: 'bean', ingredientCode: 'ING-2026-000001', organizationId: 'org-a', name: 'Coffee beans', shortName: null, description: '', categoryId: 'beans', ingredientType: 'RAW_INGREDIENT', baseUnitId: 'gram', standardReferenceCost: 0.8, lastPurchaseCost: 0.8, currencyCode: 'PHP', preferredSupplierId: null, shelfLifeDays: null, expiryTrackingRequired: false, batchTrackingRequired: false, reorderPoint: null, minimumStock: null, targetStock: null, maximumStock: null, negativeInventoryAllowed: false, storageClass: 'DRY', defaultStorageLocationId: null, active: true, status: 'ACTIVE', notes: '', createdAt: now, createdBy: 'owner', updatedAt: now, updatedBy: 'owner' }

describe('Ingredient Master Part 1', () => {
  it('validates category creation and hierarchy', () => { expect(() => validateIngredientCategory(category, [])).not.toThrow(); expect(() => validateIngredientCategory({ ...category, parentCategoryId: 'missing' }, [category])).toThrow() })
  it('requires organization-unique immutable ingredient codes', () => { expect(() => validateIngredientMaster(ingredient, [ingredient])).not.toThrow(); expect(() => validateIngredientMaster({ ...ingredient, id: 'bean-2' }, [ingredient])).toThrow(); expect(() => validateIngredientMaster({ ...ingredient, id: 'bean-2', organizationId: 'org-b' }, [ingredient])).not.toThrow() })
  it('enforces permissions and emits lifecycle events without stock creation', async () => { const records: IngredientMaster[] = []; const service = createIngredientMasterService({ async getByCode() { return null }, async list(organizationId) { return records.filter((item) => item.organizationId === organizationId) }, async create(value) { records.push(value); return value }, async update() { return undefined } }, { async list() { return [category] }, async create(value) { return value }, async update() { return undefined } }); await expect(service.create(ingredient, [])).rejects.toThrow('Permission denied'); const event = await service.create(ingredient, ['ingredients.manage']); expect(event.type).toBe('IngredientCreated'); expect(records).toHaveLength(1); expect(records[0]).not.toHaveProperty('quantity'); const deactivated = await service.setActive(ingredient, false, 'owner', ['ingredients.manage']); expect(deactivated.type).toBe('IngredientDeactivated') })
})
