import assert from 'node:assert/strict'
import test from 'node:test'
test('Firestore emulator transaction and cleanup fixture', { skip: !process.env.FIRESTORE_EMULATOR_HOST }, async () => { const { getAdminFirestore } = await import('../lib/shared/admin.js'); const firestore = getAdminFirestore(); const reference = firestore.collection('_emulatorTests').doc('transaction'); await firestore.runTransaction(async (transaction) => { transaction.set(reference, { value: 1 }) }); assert.equal((await reference.get()).data()?.value, 1); await reference.delete(); assert.equal((await reference.get()).exists, false) })
test('server finance, loyalty, and shift repositories persist duplicate-safe evidence', { skip: !process.env.FIRESTORE_EMULATOR_HOST }, async () => {
  const { getAdminFirestore } = await import('../lib/shared/admin.js'); const { JournalRepository } = await import('../lib/finance/journalRepository.js'); const { LoyaltyBalanceRepository } = await import('../lib/loyalty/loyaltyBalanceRepository.js'); const { CustomerRepository } = await import('../lib/loyalty/customerRepository.js'); const { ShiftTotalsRepository } = await import('../lib/shifts/shiftTotalsRepository.js'); const db = getAdminFirestore(); const now = new Date(); const organizationId = 'test-org-finance'; const branchId = 'test-branch-finance'; const saleId = 'test-sale-finance'; const customerId = 'test-customer-finance'; const shiftId = 'test-shift-finance';
  await db.collection('customers').doc(customerId).set({ organizationId, active: true, displayName: 'Test Customer' }); const customers = new CustomerRepository(db); assert.equal((await customers.resolveCustomerSnapshot(organizationId, branchId, customerId)).customerId, customerId)
  const journals = new JournalRepository(db); await db.runTransaction(async (transaction) => { journals.createBalanced(transaction, { saleId, organizationId, branchId, periodId: 'period', idempotencyKey: 'key', createdBy: 'user', lines: [{ accountId: 'cash', debit: 100, credit: 0, description: 'Cash' }, { accountId: 'revenue', debit: 0, credit: 100, description: 'Revenue' }] }, now) }); assert.equal((await db.collection('journalEntries').doc(`SALE-${saleId}`).get()).data()?.status, 'POSTED')
  const balances = new LoyaltyBalanceRepository(db); const balance = await balances.getBalance(organizationId, customerId); await db.runTransaction(async (transaction) => { balances.applyEarn(transaction, balance, 10, now) }); assert.equal((await balances.getBalance(organizationId, customerId)).availablePoints, 10)
  await db.collection('shifts').doc(shiftId).set({ organizationId, status: 'OPEN' }); const shifts = new ShiftTotalsRepository(db); const snapshot = { saleId, organizationId, branchId, shiftId, currencyCode: 'PHP', grossSales: 100, discounts: 0, netSales: 90, tax: 10, confirmedCogs: 30, provisionalCogs: 0, payments: [{ settlementCategory: 'CASH', amount: 100 }] }; await db.runTransaction(async (transaction) => { await shifts.applyCommittedSaleOnce(transaction, db.collection('shiftTotals').doc(shiftId), snapshot, now) }); await db.runTransaction(async (transaction) => { assert.equal(await shifts.applyCommittedSaleOnce(transaction, db.collection('shiftTotals').doc(shiftId), snapshot, now), false) }); const totals = (await db.collection('shiftTotals').doc(shiftId).get()).data(); assert.equal(totals?.transactionCount, 1); assert.equal(totals?.expectedCash, 100)
  await Promise.all([db.collection('customers').doc(customerId).delete(), db.collection('journalEntries').doc(`SALE-${saleId}`).delete(), db.collection('journalLines').doc(`SALE-${saleId}-1`).delete(), db.collection('journalLines').doc(`SALE-${saleId}-2`).delete(), db.collection('loyaltyBalances').doc(customerId).delete(), db.collection('shifts').doc(shiftId).delete(), db.collection('shiftTotals').doc(shiftId).delete(), db.collection('appliedShiftSales').doc(`${shiftId}-${saleId}`).delete()])
})
