import assert from 'node:assert/strict'
import test from 'node:test'
import { seedTrustedShiftValidationFixture } from './fixtures/trustedSaleFixture.mjs'

const guarded = ['orders', 'receipts', 'payments', 'saleIdempotency', 'stockMovements', 'inventoryBalances', 'shiftTotals', 'journalEntries', 'loyaltyTransactions', 'auditLogs', 'outboxEvents', 'cashierSaleSummaries', 'appliedShiftSales']
const endpoint = () => `http://127.0.0.1:5001/${process.env.GCLOUD_PROJECT ?? 'demo-no-project'}/asia-southeast1/completeSale`
async function counts(db) { return Object.fromEntries(await Promise.all(guarded.map(async (name) => [name, (await db.collection(name).get()).size]))) }
async function signIn(auth, fixture) { const custom = await auth.createCustomToken(fixture.cashierId, { organizationId: fixture.organizationId, branchId: fixture.branchId, employeeId: fixture.cashierId, permissions: ['sales.complete'] }); const response = await fetch('http://127.0.0.1:9099/identitytoolkit.googleapis.com/v1/accounts:signInWithCustomToken?key=emulator', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ token: custom, returnSecureToken: true }) }); const body = await response.json(); assert.equal(response.status, 200, JSON.stringify(body)); return body.idToken }
async function invoke(token, fixture, key, payments) { const response = await fetch(endpoint(), { method: 'POST', headers: { 'content-type': 'application/json', authorization: `Bearer ${token}` }, body: JSON.stringify({ data: { idempotencyKey: key, requestedBranchId: fixture.branchId, shiftId: fixture.openShiftId, cartLines: [{ clientLineId: key, productId: fixture.productId, quantity: 1 }], payments } }) }); return { response, body: await response.json() } }
const payment = (id, amount, extra = {}) => ({ paymentMethodId: id, amount, currencyCode: 'PHP', ...extra })
function assertDenied(result) { assert.ok(result.response.status >= 400, JSON.stringify(result.body)); assert.ok(result.body.error?.details?.correlationId); const serialized = JSON.stringify(result.body); assert.equal(serialized.includes('stack'), false); assert.equal(serialized.includes('projects/'), false) }
async function seedMethods(db, fixture) { const method = (id, code, name, settlementCategory, extra = {}) => db.collection('paymentMethods').doc(id).set({ organizationId: fixture.organizationId, code, name, active: true, settlementCategory, currencyCode: 'PHP', financialAccountId: `${id}-account`, ...extra }); await db.collection('inventoryBatches').doc(fixture.batchId).set({ remainingQuantity: 100 }, { merge: true }); await Promise.all([method('pay-gcash', 'GCASH', 'GCash', 'GCASH', { requiresTransactionReference: true, transactionReferencePattern: '^[A-Z0-9]{6,}$', requiresFinancialAccount: true }), method('pay-maya', 'MAYA', 'Maya', 'MAYA', { requiresTransactionReference: true }), method('pay-card', 'CARD', 'Card', 'CARD', { requiresTransactionReference: true }), method('pay-bank', 'BANK', 'Bank transfer', 'BANK', { requiresTransactionReference: true }), method('pay-other', 'OTHER', 'Other', 'OTHER')]); return { gcash: 'pay-gcash', maya: 'pay-maya', card: 'pay-card', bank: 'pay-bank', other: 'pay-other' } }
async function cleanup(db, auth, fixture) { await db.collection('recipes').doc(fixture.recipeId).collection('versions').doc('v1').delete().catch(() => undefined); for (const collection of ['orders', 'receipts', 'payments', 'saleIdempotency', 'stockMovements', 'inventoryBalances', 'shiftTotals', 'journalEntries', 'journalLines', 'loyaltyTransactions', 'loyaltyBalances', 'auditLogs', 'outboxEvents', 'cashierSaleSummaries', 'appliedShiftSales', 'organizations', 'branches', 'employees', 'employeeBranchAssignments', 'shifts', 'productCategories', 'products', 'recipes', 'taxProfiles', 'taxConfigurationVersions', 'paymentMethods', 'ingredients', 'inventoryBatches']) { const snapshot = await db.collection(collection).get(); await Promise.all(snapshot.docs.filter((entry) => entry.data().organizationId === fixture.organizationId || entry.id.includes(fixture.organizationId) || entry.id.includes(fixture.branchId)).map((entry) => entry.ref.delete())) } await db.collection('saleCounters').doc(`${fixture.organizationId}_${fixture.branchId}`).delete().catch(() => undefined); await auth.deleteUser(fixture.cashierId).catch(() => undefined) }

test('completeSale resolves authoritative payment methods, cash change, splits, snapshots, and retries', { skip: !process.env.FIRESTORE_EMULATOR_HOST }, async () => {
  const { getAdminFirestore } = await import('../lib/shared/admin.js'); const { getAuth } = await import('firebase-admin/auth'); const db = getAdminFirestore(); const auth = getAuth(); const fixture = await seedTrustedShiftValidationFixture(db, auth, { prefix: 'payment-resolution' }); const methods = await seedMethods(db, fixture); const token = await signIn(auth, fixture)
  try {
    let result = await invoke(token, fixture, 'payment-cash-exact', [payment(fixture.paymentMethodId, 110, { tenderedAmount: 110, paymentMethodName: 'forged', settlementCategory: 'FORGED', financialAccountId: 'forged', changeAmount: 999 })]); assert.equal(result.response.status, 200, JSON.stringify(result.body)); let docs = await db.collection('payments').where('saleId', '==', result.body.result.saleId).get(); assert.equal(docs.size, 1); let persisted = docs.docs[0].data(); assert.equal(persisted.paymentMethodCode, 'CASH'); assert.equal(persisted.paymentMethodName, 'Cash'); assert.equal(persisted.settlementCategory, 'CASH'); assert.equal(persisted.changeAmount, 0); assert.ok(persisted.correlationId); let receipt = (await db.collection('receipts').doc(result.body.result.saleId).get()).data(); assert.equal(receipt.payments[0].financialAccountId, undefined)
    result = await invoke(token, fixture, 'payment-cash-change', [payment(fixture.paymentMethodId, 200, { tenderedAmount: 200 })]); assert.equal(result.response.status, 200, JSON.stringify(result.body)); assert.equal(result.body.result.changeAmount, 90); persisted = (await db.collection('payments').where('saleId', '==', result.body.result.saleId).get()).docs[0].data(); assert.equal(persisted.amount, 110); assert.equal(persisted.tenderedAmount, 200); assert.equal(persisted.changeAmount, 90)
    for (const [key, methodId, reference] of [['payment-gcash', methods.gcash, 'GCASH01'], ['payment-maya', methods.maya, 'MAYA001'], ['payment-card', methods.card, 'CARD001'], ['payment-bank', methods.bank, 'BANK001'], ['payment-other', methods.other, undefined]]) { result = await invoke(token, fixture, key, [payment(methodId, 110, reference ? { transactionReference: reference } : {})]); assert.equal(result.response.status, 200, JSON.stringify(result.body)); persisted = (await db.collection('payments').where('saleId', '==', result.body.result.saleId).get()).docs[0].data(); assert.equal(persisted.paymentMethodId, methodId); assert.equal(persisted.transactionReference ?? null, reference ?? null) }
    result = await invoke(token, fixture, 'payment-split-cash-gcash', [payment(fixture.paymentMethodId, 50, { tenderedAmount: 50 }), payment(methods.gcash, 60, { transactionReference: 'GCASH02' })]); assert.equal(result.response.status, 200, JSON.stringify(result.body)); docs = await db.collection('payments').where('saleId', '==', result.body.result.saleId).get(); assert.equal(docs.size, 2); assert.deepEqual(docs.docs.map((entry) => entry.data().settlementCategory).sort(), ['CASH', 'GCASH']); const firstSaleId = result.body.result.saleId; const firstPayment = docs.docs.map((entry) => entry.data()).sort((left, right) => left.paymentMethodId.localeCompare(right.paymentMethodId)); const retry = await invoke(token, fixture, 'payment-split-cash-gcash', [payment(fixture.paymentMethodId, 50, { tenderedAmount: 50 }), payment(methods.gcash, 60, { transactionReference: 'GCASH02' })]); assert.equal(retry.response.status, 200); assert.equal(retry.body.result.saleId, firstSaleId); assert.deepEqual((await db.collection('payments').where('saleId', '==', firstSaleId).get()).docs.map((entry) => entry.data()).sort((left, right) => left.paymentMethodId.localeCompare(right.paymentMethodId)), firstPayment)
    result = await invoke(token, fixture, 'payment-split-cash-card', [payment(fixture.paymentMethodId, 40, { tenderedAmount: 40 }), payment(methods.card, 70, { transactionReference: 'CARD002' })]); assert.equal(result.response.status, 200, JSON.stringify(result.body)); docs = await db.collection('payments').where('saleId', '==', result.body.result.saleId).get(); assert.deepEqual(docs.docs.map((entry) => entry.data().settlementCategory).sort(), ['CARD', 'CASH'])
    result = await invoke(token, fixture, 'payment-split-three-methods', [payment(fixture.paymentMethodId, 20, { tenderedAmount: 20 }), payment(methods.gcash, 50, { transactionReference: 'GCASH03' }), payment(methods.other, 40)]); assert.equal(result.response.status, 200, JSON.stringify(result.body)); docs = await db.collection('payments').where('saleId', '==', result.body.result.saleId).get(); assert.deepEqual(docs.docs.map((entry) => entry.data().settlementCategory).sort(), ['CASH', 'GCASH', 'OTHER'])
    await db.collection('paymentMethods').doc(methods.gcash).set({ name: 'Changed GCash', settlementCategory: 'OTHER', financialAccountId: 'changed-account' }, { merge: true }); const unchanged = (await db.collection('payments').where('saleId', '==', firstSaleId).get()).docs.find((entry) => entry.data().paymentMethodId === methods.gcash)?.data(); assert.equal(unchanged.paymentMethodName, 'GCash'); assert.equal(unchanged.settlementCategory, 'GCASH')
  } finally { await cleanup(db, auth, fixture) }
})

test('completeSale rejects invalid server payment configuration and tender combinations before effects', { skip: !process.env.FIRESTORE_EMULATOR_HOST }, async () => {
  const { getAdminFirestore } = await import('../lib/shared/admin.js'); const { getAuth } = await import('firebase-admin/auth'); const db = getAdminFirestore(); const auth = getAuth(); const fixture = await seedTrustedShiftValidationFixture(db, auth, { prefix: 'payment-denial' }); const methods = await seedMethods(db, fixture); const token = await signIn(auth, fixture)
  try {
    const reject = async (key, payments) => { const before = await counts(db); const result = await invoke(token, fixture, key, payments); assertDenied(result); assert.deepEqual(await counts(db), before, `${key} must not create effects`) }
    await reject('payment-unknown', [payment('missing-payment', 110)])
    await db.collection('paymentMethods').doc(methods.gcash).set({ active: false }, { merge: true }); await reject('payment-inactive', [payment(methods.gcash, 110, { transactionReference: 'GCASH01' })]); await db.collection('paymentMethods').doc(methods.gcash).set({ active: true }, { merge: true })
    await db.collection('paymentMethods').doc(methods.gcash).set({ branchIds: ['other-branch'] }, { merge: true }); await reject('payment-other-branch', [payment(methods.gcash, 110, { transactionReference: 'GCASH01' })]); await db.collection('paymentMethods').doc(methods.gcash).set({ branchIds: null }, { merge: true })
    await reject('payment-currency', [payment(methods.gcash, 110, { currencyCode: 'USD', transactionReference: 'GCASH01' })]); await reject('payment-missing-reference', [payment(methods.gcash, 110)]); await reject('payment-invalid-reference', [payment(methods.gcash, 110, { transactionReference: 'bad' })]); await reject('payment-noncash-tender', [payment(methods.gcash, 110, { transactionReference: 'GCASH01', tenderedAmount: 110 })]); await reject('payment-cash-insufficient', [payment(fixture.paymentMethodId, 100, { tenderedAmount: 100 })]); await reject('payment-split-under', [payment(fixture.paymentMethodId, 40, { tenderedAmount: 40 }), payment(methods.gcash, 50, { transactionReference: 'GCASH01' })]); await reject('payment-split-over', [payment(methods.gcash, 111, { transactionReference: 'GCASH01' })]); await reject('payment-duplicate-method', [payment(methods.other, 55), payment(methods.other, 55)])
    await db.collection('paymentMethods').doc(fixture.paymentMethodId).set({ requiresTenderedAmount: true }, { merge: true }); await reject('payment-missing-cash-tender', [payment(fixture.paymentMethodId, 110)]); await db.collection('paymentMethods').doc(fixture.paymentMethodId).set({ requiresTenderedAmount: false }, { merge: true })
    await db.collection('paymentMethods').doc(methods.gcash).set({ effectiveFrom: new Date('2099-01-01') }, { merge: true }); await reject('payment-not-effective', [payment(methods.gcash, 110, { transactionReference: 'GCASH01' })]); await db.collection('paymentMethods').doc(methods.gcash).set({ effectiveFrom: null, effectiveTo: new Date('2000-01-01') }, { merge: true }); await reject('payment-expired', [payment(methods.gcash, 110, { transactionReference: 'GCASH01' })]); await db.collection('paymentMethods').doc(methods.gcash).set({ effectiveTo: null, requiresFinancialAccount: true, financialAccountId: null }, { merge: true }); await reject('payment-missing-account', [payment(methods.gcash, 110, { transactionReference: 'GCASH01' })]); await db.collection('paymentMethods').doc(methods.gcash).set({ requiresFinancialAccount: false, financialAccountId: 'gcash-account', settlementCategory: 'INVALID' }, { merge: true }); await reject('payment-invalid-settlement', [payment(methods.gcash, 110, { transactionReference: 'GCASH01' })])
  } finally { await cleanup(db, auth, fixture) }
})
