import assert from 'node:assert/strict'
import test from 'node:test'
import { seedTrustedShiftValidationFixture } from './fixtures/trustedSaleFixture.mjs'

const trustedCollections = ['orders', 'receipts', 'payments', 'saleIdempotency', 'stockMovements', 'inventoryBalances', 'shiftTotals', 'journalEntries', 'loyaltyTransactions', 'auditLogs', 'outboxEvents', 'cashierSaleSummaries', 'appliedShiftSales']
const callableUrl = () => `http://127.0.0.1:5001/${process.env.GCLOUD_PROJECT ?? 'demo-no-project'}/asia-southeast1/completeSale`
async function counts(db) { return Object.fromEntries(await Promise.all(trustedCollections.map(async (name) => [name, (await db.collection(name).get()).size]))) }
async function tokenFor(auth, fixture) { const token = await auth.createCustomToken(fixture.cashierId, { organizationId: fixture.organizationId, branchId: fixture.branchId, employeeId: fixture.cashierId, permissions: ['sales.complete'] }); const response = await fetch('http://127.0.0.1:9099/identitytoolkit.googleapis.com/v1/accounts:signInWithCustomToken?key=emulator', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ token, returnSecureToken: true }) }); const body = await response.json(); assert.equal(response.status, 200, JSON.stringify(body)); return body.idToken }
async function invoke(token, fixture, key, line = {}) { const response = await fetch(callableUrl(), { method: 'POST', headers: { 'content-type': 'application/json', authorization: `Bearer ${token}` }, body: JSON.stringify({ data: { idempotencyKey: key, requestedBranchId: fixture.branchId, shiftId: fixture.openShiftId, cartLines: [{ clientLineId: key, productId: fixture.productId, quantity: 1, ...line }], payments: [{ paymentMethodId: fixture.paymentMethodId, amount: 200, tenderedAmount: 200, currencyCode: 'PHP' }] } }) }); return { response, body: await response.json() } }
function assertDenied(result) { assert.ok(result.response.status >= 400, JSON.stringify(result.body)); assert.ok(result.body.error?.details?.correlationId); const serialized = JSON.stringify(result.body); assert.equal(serialized.includes('stack'), false); assert.equal(serialized.includes('projects/'), false) }
async function cleanup(db, auth, fixture) {
  await db.collection('recipes').doc(fixture.recipeId).collection('versions').doc('v1').delete().catch(() => undefined)
  await db.collection('recipes').doc('recipe-second-published').collection('versions').doc('v2').delete().catch(() => undefined)
  for (const collection of ['orders', 'receipts', 'payments', 'saleIdempotency', 'stockMovements', 'inventoryBalances', 'shiftTotals', 'journalEntries', 'journalLines', 'loyaltyTransactions', 'loyaltyBalances', 'auditLogs', 'outboxEvents', 'cashierSaleSummaries', 'appliedShiftSales', 'organizations', 'branches', 'employees', 'employeeBranchAssignments', 'shifts', 'productCategories', 'products', 'recipes', 'taxProfiles', 'taxConfigurationVersions', 'paymentMethods', 'ingredients', 'inventoryBatches']) { const snapshot = await db.collection(collection).get(); await Promise.all(snapshot.docs.filter((entry) => entry.data().organizationId === fixture.organizationId || entry.id.includes(fixture.organizationId) || entry.id.includes(fixture.branchId)).map((entry) => entry.ref.delete())) }
  await db.collection('saleCounters').doc(`${fixture.organizationId}_${fixture.branchId}`).delete().catch(() => undefined); await auth.deleteUser(fixture.cashierId).catch(() => undefined)
}
async function withFixture(db, auth, prefix, run) { const fixture = await seedTrustedShiftValidationFixture(db, auth, { prefix }); try { await run(fixture, await tokenFor(auth, fixture)) } finally { await cleanup(db, auth, fixture) } }

test('completeSale resolves immutable recipe evidence from the current published server recipe', { skip: !process.env.FIRESTORE_EMULATOR_HOST }, async () => {
  const { getAdminFirestore } = await import('../lib/shared/admin.js'); const { getAuth } = await import('firebase-admin/auth'); const db = getAdminFirestore(); const auth = getAuth()
  await withFixture(db, auth, 'recipe-current', async (fixture, token) => {
    await db.collection('recipes').doc(fixture.recipeId).collection('versions').doc('v1').set({ businessVersion: '2026.1' }, { merge: true })
    const result = await invoke(token, fixture, 'recipe-current-sale', { recipeId: 'forged-recipe', recipeVersionId: 'forged-version', ingredientRequirements: [{ ingredientId: 'forged', baseUnitQuantity: 99 }], ingredientQuantities: { [fixture.ingredientId]: 99 }, substitutions: [{ ingredientId: fixture.ingredientId, replacementIngredientId: 'forged' }] })
    assert.equal(result.response.status, 200, JSON.stringify(result.body)); const sale = (await db.collection('orders').doc(result.body.result.saleId).get()).data(); const line = sale?.lines[0]
    assert.equal(line?.recipeSnapshot.recipeId, fixture.recipeId); assert.equal(line?.recipeSnapshot.recipeVersionId, 'v1'); assert.equal(line?.recipeSnapshot.businessVersion, '2026.1'); assert.equal(line?.recipeSnapshot.ingredientRequirements[0].ingredientId, fixture.ingredientId); assert.equal(line?.recipeSnapshot.ingredientRequirements[0].baseUnitQuantity, 2); assert.equal(sale?.confirmedCogs, 4); assert.equal(sale?.cogsStatus, 'CONFIRMED')
    const movement = (await db.collection('stockMovements').where('saleId', '==', result.body.result.saleId).get()).docs[0]?.data(); assert.equal(movement?.ingredientId, fixture.ingredientId); assert.equal(movement?.quantity, 2); assert.equal(movement?.totalCost, 4)
  })
  const denied = async (prefix, mutate) => withFixture(db, auth, prefix, async (fixture, token) => { await mutate(fixture); const before = await counts(db); const result = await invoke(token, fixture, prefix); assertDenied(result); assert.deepEqual(await counts(db), before, `${prefix} must not persist trusted sale effects`) })
  await denied('recipe-no-published', async (fixture) => { await db.collection('recipes').doc(fixture.recipeId).set({ published: false, recipeStatus: 'DRAFT' }, { merge: true }) })
  await denied('recipe-draft', async (fixture) => { await db.collection('recipes').doc(fixture.recipeId).set({ published: false, recipeStatus: 'DRAFT' }, { merge: true }); await db.collection('recipes').doc(fixture.recipeId).collection('versions').doc('v1').set({ status: 'draft' }, { merge: true }) })
  await denied('recipe-archived', async (fixture) => { await db.collection('recipes').doc(fixture.recipeId).set({ published: false, recipeStatus: 'ARCHIVED' }, { merge: true }) })
  await denied('recipe-deleted', async (fixture) => { await db.collection('recipes').doc(fixture.recipeId).delete() })
  await denied('recipe-other-product', async (fixture) => { await db.collection('recipes').doc(fixture.recipeId).set({ productId: 'another-product' }, { merge: true }) })
  await denied('recipe-multiple-published', async (fixture) => { await db.collection('recipes').doc('recipe-second-published').set({ organizationId: fixture.organizationId, recipeNumber: 'R-2', productId: fixture.productId, recipeName: 'Second', published: true, recipeStatus: 'PUBLISHED', activeVersionId: 'v2' }); await db.collection('recipes').doc('recipe-second-published').collection('versions').doc('v2').set({ organizationId: fixture.organizationId, recipeId: 'recipe-second-published', businessVersion: '2', status: 'published', ingredients: [{ ingredientId: fixture.ingredientId, ingredientNameSnapshot: 'Beans', baseUnitQuantity: 2, unitId: 'g', optional: false }], yieldQuantity: 1, yieldUnitId: 'piece' }) })
})
