import assert from 'node:assert/strict'
import test from 'node:test'
import { seedTrustedShiftValidationFixture } from './fixtures/trustedSaleFixture.mjs'

const protectedCollections = ['orders', 'receipts', 'payments', 'saleIdempotency', 'stockMovements', 'inventoryBalances', 'shiftTotals', 'journalEntries', 'loyaltyTransactions', 'auditLogs', 'outboxEvents', 'cashierSaleSummaries', 'appliedShiftSales']
const callableUrl = () => `http://127.0.0.1:5001/${process.env.GCLOUD_PROJECT ?? 'demo-no-project'}/asia-southeast1/completeSale`
const taxVersion = (organizationId, taxProfileId, rate, calculationMode = 'TAX_EXCLUSIVE', active = true, effectiveFrom = new Date('2025-01-01'), effectiveTo = null) => ({ organizationId, taxProfileId, rate, calculationMode, roundingMethod: 'HALF_UP', roundingPrecision: 2, active, effectiveFrom, effectiveTo })
async function counts(db) { return Object.fromEntries(await Promise.all(protectedCollections.map(async (name) => [name, (await db.collection(name).get()).size]))) }
async function tokenFor(auth, fixture) { const token = await auth.createCustomToken(fixture.cashierId, { organizationId: fixture.organizationId, branchId: fixture.branchId, employeeId: fixture.cashierId, permissions: ['sales.complete'] }); const response = await fetch('http://127.0.0.1:9099/identitytoolkit.googleapis.com/v1/accounts:signInWithCustomToken?key=emulator', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ token, returnSecureToken: true }) }); const body = await response.json(); assert.equal(response.status, 200, JSON.stringify(body)); return body.idToken }
async function invoke(token, fixture, key, line = {}, extra = {}) { const response = await fetch(callableUrl(), { method: 'POST', headers: { 'content-type': 'application/json', authorization: `Bearer ${token}` }, body: JSON.stringify({ data: { idempotencyKey: key, requestedBranchId: fixture.branchId, shiftId: fixture.openShiftId, cartLines: [{ clientLineId: key, productId: fixture.productId, quantity: 1, ...line }], payments: [{ paymentMethodId: fixture.paymentMethodId, amount: 200, tenderedAmount: 200, currencyCode: 'PHP' }], ...extra } }) }); return { response, body: await response.json() } }
function assertDenied(result) { assert.ok(result.response.status >= 400, JSON.stringify(result.body)); assert.ok(result.body.error?.details?.correlationId); const serialized = JSON.stringify(result.body); assert.equal(serialized.includes('stack'), false); assert.equal(serialized.includes('projects/'), false) }
async function cleanup(db, auth, fixture) { await db.collection('recipes').doc(fixture.recipeId).collection('versions').doc('v1').delete().catch(() => undefined); for (const collection of ['orders', 'receipts', 'payments', 'saleIdempotency', 'stockMovements', 'inventoryBalances', 'shiftTotals', 'journalEntries', 'journalLines', 'loyaltyTransactions', 'loyaltyBalances', 'auditLogs', 'outboxEvents', 'cashierSaleSummaries', 'appliedShiftSales', 'productVariations', 'optionGroups', 'optionItems', 'productOptionAssignments', 'taxAssignments', 'organizations', 'branches', 'employees', 'employeeBranchAssignments', 'shifts', 'productCategories', 'products', 'recipes', 'taxProfiles', 'taxConfigurationVersions', 'paymentMethods', 'ingredients', 'inventoryBatches']) { const snapshot = await db.collection(collection).get(); await Promise.all(snapshot.docs.filter((entry) => entry.data().organizationId === fixture.organizationId || entry.id.includes(fixture.organizationId) || entry.id.includes(fixture.branchId)).map((entry) => entry.ref.delete())) } await db.collection('saleCounters').doc(`${fixture.organizationId}_${fixture.branchId}`).delete().catch(() => undefined); await auth.deleteUser(fixture.cashierId).catch(() => undefined) }
async function profile(db, fixture, id, rate, type = 'STANDARD', mode = 'TAX_EXCLUSIVE') { await db.collection('taxProfiles').doc(id).set({ organizationId: fixture.organizationId, code: id.toUpperCase(), name: id, taxType: type, active: true, priority: 1, defaultForOrganization: false }); await db.collection('taxConfigurationVersions').doc(`${id}-v1`).set(taxVersion(fixture.organizationId, id, rate, mode)); return id }

test('completeSale resolves tax precedence, effective versions, modes, and immutable server snapshots', { skip: !process.env.FIRESTORE_EMULATOR_HOST }, async () => {
  const { getAdminFirestore } = await import('../lib/shared/admin.js'); const { getAuth } = await import('firebase-admin/auth'); const db = getAdminFirestore(); const auth = getAuth(); const fixture = await seedTrustedShiftValidationFixture(db, auth, { prefix: 'tax-resolution' }); const token = await tokenFor(auth, fixture)
  try {
    await db.collection('inventoryBatches').doc(fixture.batchId).set({ remainingQuantity: 100 }, { merge: true }); await db.collection('products').doc(fixture.productId).set({ taxProfileId: null }, { merge: true }); await Promise.all([db.collection('taxConfigurationVersions').doc(`${fixture.taxProfileId}-expired`).set(taxVersion(fixture.organizationId, fixture.taxProfileId, '0.9', 'TAX_EXCLUSIVE', true, new Date('2020-01-01'), new Date('2021-01-01'))), db.collection('taxConfigurationVersions').doc(`${fixture.taxProfileId}-future`).set(taxVersion(fixture.organizationId, fixture.taxProfileId, '0.9', 'TAX_EXCLUSIVE', true, new Date('2099-01-01'))), db.collection('taxConfigurationVersions').doc(`${fixture.taxProfileId}-disabled`).set(taxVersion(fixture.organizationId, fixture.taxProfileId, '0.9', 'TAX_EXCLUSIVE', false))])
    const branch = await profile(db, fixture, 'tax-branch', '0.01'); const category = await profile(db, fixture, 'tax-category', '0.02'); const product = await profile(db, fixture, 'tax-product', '0.03'); const variation = await profile(db, fixture, 'tax-variation', '0.04'); const option = await profile(db, fixture, 'tax-option', '0.05')
    const assignment = (id, scope, scopeId, taxProfileId) => db.collection('taxAssignments').doc(id).set({ organizationId: fixture.organizationId, scope, scopeId, taxProfileId, active: true })
    await assignment('tax-branch-assignment', 'BRANCH', fixture.branchId, branch)
    let result = await invoke(token, fixture, 'tax-branch-wins', {}, { taxRate: 0, taxProfileId: 'forged', taxConfigurationVersionId: 'forged', taxAmount: 0, taxableAmount: 0, calculationMode: 'NOT_APPLICABLE', taxAccountId: 'forged' }); assert.equal(result.response.status, 200, JSON.stringify(result.body)); let sale = (await db.collection('orders').doc(result.body.result.saleId).get()).data(); assert.equal(sale.lines[0].taxSnapshot.taxProfileId, branch); assert.equal(sale.lines[0].taxSnapshot.rateApplied, '0.01')
    await assignment('tax-category-assignment', 'CATEGORY', fixture.categoryId, category); result = await invoke(token, fixture, 'tax-category-wins'); sale = (await db.collection('orders').doc(result.body.result.saleId).get()).data(); assert.equal(sale.lines[0].taxSnapshot.taxProfileId, category)
    await assignment('tax-product-assignment', 'PRODUCT', fixture.productId, product); result = await invoke(token, fixture, 'tax-product-wins'); sale = (await db.collection('orders').doc(result.body.result.saleId).get()).data(); assert.equal(sale.lines[0].taxSnapshot.taxProfileId, product)
    const variationId = 'tax-variation-size'; await db.collection('productVariations').doc(variationId).set({ organizationId: fixture.organizationId, productId: fixture.productId, code: 'TAX-VAR', name: 'Tax variation', variationType: 'SIZE', sellingPrice: 100, active: true, status: 'PUBLISHED', default: false }); await db.collection('recipes').doc(fixture.recipeId).set({ productVariationId: variationId }, { merge: true }); await assignment('tax-variation-assignment', 'VARIATION', variationId, variation); result = await invoke(token, fixture, 'tax-variation-wins', { variationId }); sale = (await db.collection('orders').doc(result.body.result.saleId).get()).data(); assert.equal(sale.lines[0].taxSnapshot.taxProfileId, variation)
    const groupId = 'tax-option-group'; const optionId = 'tax-option-item'; await Promise.all([db.collection('optionGroups').doc(groupId).set({ organizationId: fixture.organizationId, code: 'TAX-OPTION', name: 'Tax option', selectionType: 'SINGLE', minimumSelections: 0, maximumSelections: 1, required: false, active: true }), db.collection('optionItems').doc(optionId).set({ organizationId: fixture.organizationId, modifierGroupId: groupId, code: 'TAX-OPTION', name: 'Tax option', priceAdjustment: 20, recipeAdjustmentType: 'NONE', ingredientEffects: [], active: true, maximumQuantity: 1 }), db.collection('productOptionAssignments').doc('tax-option-assignment').set({ organizationId: fixture.organizationId, productId: fixture.productId, optionGroupId: groupId, active: true })]); await assignment('tax-option-item-assignment', 'OPTION', optionId, option); result = await invoke(token, fixture, 'tax-option-wins', { variationId, selectedOptionItemIds: [{ optionItemId: optionId }] }); sale = (await db.collection('orders').doc(result.body.result.saleId).get()).data(); assert.equal(sale.lines[0].taxSnapshot.taxProfileId, variation); assert.equal(sale.lines[0].optionTaxSnapshots[0].taxProfileId, option); assert.equal(sale.taxAmount, 5)

    await db.collection('taxProfiles').doc(fixture.taxProfileId).set({ defaultForOrganization: true, active: true, taxType: 'STANDARD' }, { merge: true }); await db.collection('taxConfigurationVersions').doc(`${fixture.taxProfileId}-v1`).set(taxVersion(fixture.organizationId, fixture.taxProfileId, '0.1', 'TAX_INCLUSIVE'), { merge: true }); await Promise.all(['tax-branch-assignment', 'tax-category-assignment', 'tax-product-assignment', 'tax-variation-assignment', 'tax-option-item-assignment'].map((id) => db.collection('taxAssignments').doc(id).delete())); await Promise.all(['expired', 'future', 'disabled'].map((suffix) => db.collection('taxConfigurationVersions').doc(`${fixture.taxProfileId}-${suffix}`).delete())); await db.collection('products').doc(fixture.productId).set({ taxProfileId: fixture.taxProfileId, baseSellingPrice: 110 }, { merge: true }); await db.collection('recipes').doc(fixture.recipeId).set({ productVariationId: null }, { merge: true }); result = await invoke(token, fixture, 'tax-inclusive-mode'); assert.equal(result.response.status, 200, JSON.stringify(result.body)); sale = (await db.collection('orders').doc(result.body.result.saleId).get()).data(); assert.equal(sale.taxAmount, 10); assert.equal(sale.grandTotal, 110); assert.equal(sale.lines[0].taxSnapshot.taxInclusiveAmount, 110); const receipt = (await db.collection('receipts').doc(result.body.result.saleId).get()).data(); assert.deepEqual(receipt.lines[0].taxSnapshot, sale.lines[0].taxSnapshot)
    const historical = sale.lines[0].taxSnapshot; await db.collection('taxConfigurationVersions').doc(`${fixture.taxProfileId}-v1`).set({ active: false }, { merge: true }); await db.collection('taxConfigurationVersions').doc(`${fixture.taxProfileId}-v2`).set(taxVersion(fixture.organizationId, fixture.taxProfileId, '0.2'), { merge: true }); result = await invoke(token, fixture, 'tax-effective-current'); sale = (await db.collection('orders').doc(result.body.result.saleId).get()).data(); assert.equal(sale.lines[0].taxSnapshot.taxConfigurationVersionId, `${fixture.taxProfileId}-v2`); assert.equal(sale.lines[0].taxSnapshot.rateApplied, '0.2'); const historicalSale = (await db.collection('orders').where('idempotencyKey', '==', 'tax-inclusive-mode').get()).docs[0].data(); assert.deepEqual(historicalSale.lines[0].taxSnapshot, historical)
    await db.collection('taxProfiles').doc(fixture.taxProfileId).set({ taxType: 'ZERO_RATED' }, { merge: true }); await db.collection('taxConfigurationVersions').doc(`${fixture.taxProfileId}-v2`).set(taxVersion(fixture.organizationId, fixture.taxProfileId, '0', 'TAX_EXCLUSIVE'), { merge: true }); result = await invoke(token, fixture, 'tax-zero-rated'); sale = (await db.collection('orders').doc(result.body.result.saleId).get()).data(); assert.equal(sale.taxAmount, 0); assert.equal(sale.lines[0].taxSnapshot.zeroRatedAmount, 110)
    await db.collection('taxProfiles').doc(fixture.taxProfileId).set({ taxType: 'EXEMPT' }, { merge: true }); await db.collection('taxConfigurationVersions').doc(`${fixture.taxProfileId}-v2`).set(taxVersion(fixture.organizationId, fixture.taxProfileId, '0', 'NOT_APPLICABLE'), { merge: true }); result = await invoke(token, fixture, 'tax-exempt'); sale = (await db.collection('orders').doc(result.body.result.saleId).get()).data(); assert.equal(sale.taxAmount, 0); assert.equal(sale.lines[0].taxSnapshot.exemptAmount, 110)
  } finally { await cleanup(db, auth, fixture) }
})

test('completeSale rejects invalid or inapplicable trusted tax configuration before effects', { skip: !process.env.FIRESTORE_EMULATOR_HOST }, async () => {
  const { getAdminFirestore } = await import('../lib/shared/admin.js'); const { getAuth } = await import('firebase-admin/auth'); const db = getAdminFirestore(); const auth = getAuth(); const fixture = await seedTrustedShiftValidationFixture(db, auth, { prefix: 'tax-denial' }); const token = await tokenFor(auth, fixture)
  try {
    const reject = async (key) => { const before = await counts(db); const result = await invoke(token, fixture, key); assertDenied(result); assert.deepEqual(await counts(db), before, `${key} must not create trusted sale effects`) }
    await db.collection('products').doc(fixture.productId).set({ taxProfileId: 'tax-missing-profile' }, { merge: true }); await reject('tax-missing-profile')
    await db.collection('taxProfiles').doc(fixture.taxProfileId).set({ active: false }, { merge: true }); await db.collection('products').doc(fixture.productId).set({ taxProfileId: fixture.taxProfileId }, { merge: true }); await reject('tax-inactive-profile')
    await db.collection('taxProfiles').doc(fixture.taxProfileId).set({ active: true, branchIds: ['another-branch'] }, { merge: true }); await reject('tax-invalid-branch-override')
    await db.collection('taxProfiles').doc(fixture.taxProfileId).set({ branchIds: null }, { merge: true }); await db.collection('taxConfigurationVersions').doc(`${fixture.taxProfileId}-v1`).set({ active: false }, { merge: true }); await reject('tax-missing-effective-version')
    await db.collection('taxConfigurationVersions').doc(`${fixture.taxProfileId}-v1`).set(taxVersion(fixture.organizationId, fixture.taxProfileId, '-1'), { merge: true }); await reject('tax-invalid-rate')
    await db.collection('taxConfigurationVersions').doc(`${fixture.taxProfileId}-v1`).set(taxVersion(fixture.organizationId, fixture.taxProfileId, '0.1', 'UNSUPPORTED'), { merge: true }); await reject('tax-invalid-mode')
    await db.collection('taxConfigurationVersions').doc(`${fixture.taxProfileId}-v1`).set(taxVersion(fixture.organizationId, fixture.taxProfileId, '0.1'), { merge: true }); await db.collection('taxConfigurationVersions').doc(`${fixture.taxProfileId}-overlap`).set(taxVersion(fixture.organizationId, fixture.taxProfileId, '0.2'), { merge: true }); await reject('tax-overlapping-effective-versions')
  } finally { await cleanup(db, auth, fixture) }
})
