import { consumeInventory } from '../inventory-consumption'
import type { InventoryBalance, InventoryConsumptionRequest } from '../inventory-consumption/contracts'
import type { InventoryBatch } from '../../features/procurement/domain'
import type { TaxSnapshot } from '../../features/finance'

export type TrustedSaleFailure = 'idempotency_conflict' | 'invalid_payment' | 'inventory_prohibited' | 'persistence_failure'
export interface TrustedSaleLine { id: string; productSnapshot: { productId: string; productCode: string; productName: string; variationId: string | null; variationCode: string | null; variationName: string | null; unitPrice: number; quantity: number; lineTotal: number }; taxSnapshot: TaxSnapshot; inventory: readonly { request: InventoryConsumptionRequest; batches: readonly InventoryBatch[]; balance: InventoryBalance; negativeAllowed: boolean }[] }
export interface TrustedSaleCommand { idempotencyKey: string; requestHash: string; organizationId: string; branchId: string; shiftId: string; cashierUserId: string; receiptNumber: string; payments: readonly { id: string; method: string; amount: number; reference?: string }[]; lines: readonly TrustedSaleLine[]; correlationId: string; requestedAt: Date }
export interface TrustedSaleResult { saleId: string; receiptNumber: string; confirmedCogs: number; provisionalCogs: number; cogsStatus: 'CONFIRMED' | 'PROVISIONAL' | 'MIXED' | 'UNAVAILABLE' }
export interface TrustedSaleRepository { findIdempotency(key: string): Promise<{ requestHash: string; result: TrustedSaleResult } | null>; commit(input: { idempotencyKey: string; requestHash: string; result: TrustedSaleResult; command: TrustedSaleCommand; movements: readonly { type: 'SALE_CONSUMPTION'; ingredientId: string; batchId: string | null; quantity: number; unitCost: number; provisional: boolean }[]; audit: { event: 'SaleCompleted'; correlationId: string }; events: readonly string[] }): Promise<void> }
const round = (value: number) => Math.round(value * 100) / 100
export async function trustedCompleteSale(command: TrustedSaleCommand, repository: TrustedSaleRepository): Promise<TrustedSaleResult> {
  const existing = await repository.findIdempotency(command.idempotencyKey)
  if (existing) { if (existing.requestHash !== command.requestHash) throw new Error('idempotency_conflict'); return existing.result }
  const due = round(command.lines.reduce((total, line) => total + line.productSnapshot.lineTotal, 0)); const paid = round(command.payments.reduce((total, payment) => total + payment.amount, 0)); if (!command.lines.length || paid !== due) throw new Error('invalid_payment')
  const movements: { type: 'SALE_CONSUMPTION'; ingredientId: string; batchId: string | null; quantity: number; unitCost: number; provisional: boolean }[] = []; let confirmedCogs = 0; let provisionalCogs = 0
  for (const line of command.lines) for (const requirement of line.inventory) { const result = consumeInventory(requirement.request, requirement.batches, requirement.balance); if (result.negativeQuantity > 0 && !requirement.negativeAllowed) throw new Error('inventory_prohibited'); confirmedCogs = round(confirmedCogs + result.confirmedFIFOCost); provisionalCogs = round(provisionalCogs + result.estimatedNegativeCost); for (const allocation of result.batchAllocations) movements.push({ type: 'SALE_CONSUMPTION', ingredientId: requirement.request.ingredientId, batchId: allocation.inventoryBatchId, quantity: allocation.quantity, unitCost: allocation.unitCost, provisional: false }); if (result.negativeAllocation) movements.push({ type: 'SALE_CONSUMPTION', ingredientId: requirement.request.ingredientId, batchId: null, quantity: result.negativeAllocation.quantity, unitCost: result.negativeAllocation.estimatedUnitCost, provisional: true }) }
  const result: TrustedSaleResult = { saleId: `SALE-${command.idempotencyKey}`, receiptNumber: command.receiptNumber, confirmedCogs, provisionalCogs, cogsStatus: provisionalCogs > 0 ? confirmedCogs > 0 ? 'MIXED' : 'PROVISIONAL' : 'CONFIRMED' }
  await repository.commit({ idempotencyKey: command.idempotencyKey, requestHash: command.requestHash, result, command, movements, audit: { event: 'SaleCompleted', correlationId: command.correlationId }, events: ['SaleExecutionStarted', 'SaleInventoryConsumed', 'SaleTaxCalculated', 'SalePaymentRecorded', 'SaleReceiptCreated', 'SaleCompleted'] })
  return result
}
