import { getFunctions, httpsCallable } from 'firebase/functions'
import type { CartItem, Payment } from '../../features/pos/domain'
import { firebaseApp } from '../../shared/firebase/config'
import type { CompleteSaleResult } from './contracts'

export interface TrustedSaleRequest { idempotencyKey: string; requestedBranchId: string; shiftId: string; cartLines: readonly { clientLineId: string; productId: string; quantity: number; notes: string }[]; payments: readonly { paymentMethodId: string; amount: number; currencyCode: 'PHP'; transactionReference?: string; tenderedAmount?: number }[] }
interface CallableSaleResponse { saleId: string; receiptNumber: string; grandTotal: number; changeAmount: number; cogsStatus: string; correlationId?: string }
interface CallableFailure { code?: unknown; details?: unknown }
const isRecord = (value: unknown): value is Record<string, unknown> => typeof value === 'object' && value !== null
export function toTrustedSaleRequest(input: { branchId: string; shiftId: string; items: readonly CartItem[]; payments: readonly Payment[]; idempotencyKey: string }): TrustedSaleRequest { return { idempotencyKey: input.idempotencyKey, requestedBranchId: input.branchId, shiftId: input.shiftId, cartLines: input.items.map((item) => ({ clientLineId: item.product.id, productId: item.product.id, quantity: item.quantity, notes: item.note })), payments: input.payments.map((payment) => ({ paymentMethodId: payment.method, amount: payment.amount, currencyCode: 'PHP', ...(payment.reference ? { transactionReference: payment.reference } : {}), ...(payment.method === 'cash' ? { tenderedAmount: payment.amount } : {}) })) } }
export function mapTrustedSaleFailure(error: unknown): Extract<CompleteSaleResult, { success: false }> { const failure = isRecord(error) ? error as CallableFailure : {}; const details = isRecord(failure.details) ? failure.details : {}; const correlationId = typeof details.correlationId === 'string' ? details.correlationId : undefined; const code = typeof failure.code === 'string' ? failure.code : ''; if (code.includes('permission-denied') || code.includes('unauthenticated')) return { success: false, error: { code: 'operational_error', message: 'You are not authorized to complete this sale.', recoverable: false, ...(correlationId ? { correlationId } : {}) }, warnings: [] }; if (code.includes('invalid-argument') || code.includes('failed-precondition')) return { success: false, error: { code: 'trusted_validation_error', message: 'Review the checkout details and payment before retrying.', recoverable: true, ...(correlationId ? { correlationId } : {}) }, warnings: [] }; if (code.includes('already-exists')) return { success: false, error: { code: 'idempotency_conflict', message: 'This checkout key belongs to a different sale request.', recoverable: false, ...(correlationId ? { correlationId } : {}) }, warnings: [] }; if (code.includes('deadline-exceeded') || code.includes('unavailable') || code.includes('network')) return { success: false, error: { code: 'offline_unavailable', message: 'The sales service is unavailable. Retry this same checkout when connection returns.', recoverable: true, ...(correlationId ? { correlationId } : {}) }, warnings: [] }; return { success: false, error: { code: 'persistence_error', message: 'The trusted sales service could not complete this order. Retry with the same checkout action.', recoverable: true, ...(correlationId ? { correlationId } : {}) }, warnings: [] } }

export async function submitTrustedSale(input: { branchId: string; shiftId: string; items: readonly CartItem[]; payments: readonly Payment[]; idempotencyKey: string }): Promise<CompleteSaleResult> {
  if (!firebaseApp) return { success: false, error: { code: 'offline_unavailable', message: 'Trusted sales service is not configured.', recoverable: true }, warnings: [] }
  try {
    const invoke = httpsCallable<TrustedSaleRequest, CallableSaleResponse>(getFunctions(firebaseApp, 'asia-southeast1'), 'completeSale')
    const response = await invoke(toTrustedSaleRequest(input))
    const sale = response.data
    return { success: true, orderId: sale.saleId, orderNumber: sale.receiptNumber, receipt: { number: sale.receiptNumber, orderNumber: sale.receiptNumber, business: { name: 'Accaza Coffee', address: '', tin: '', footerMessage: '' }, cashier: '', issuedAt: new Date(), items: [], summary: { subtotal: sale.grandTotal, discount: 0, vat: 0, grandTotal: sale.grandTotal, paid: sale.grandTotal, change: sale.changeAmount }, payment: { method: 'trusted', amount: sale.grandTotal } }, paymentSummary: { due: sale.grandTotal, paid: sale.grandTotal, balance: 0, change: sale.changeAmount }, total: sale.grandTotal, change: sale.changeAmount, estimatedCogs: 0, warnings: sale.cogsStatus === 'UNAVAILABLE' ? ['COGS is pending inventory allocation.'] : [] }
  } catch (error) { return mapTrustedSaleFailure(error) }
}
