import type { FeatureConfiguration, FeatureDefinition, FeatureKey } from '../domain'
const planned = (key: FeatureKey, name: string, dependencies: readonly FeatureKey[] = []): FeatureDefinition => ({ key, name, description: `${name} is planned for a later operational release.`, category: key.split('.')[0]!, defaultEnabled: false, configurableAtOrganization: true, configurableAtBranch: true, dependencies, conflicts: [], minimumRoleToConfigure: 'owner', status: 'PLANNED', createdAt: new Date(0), updatedAt: new Date(0) })
export const FEATURE_REGISTRY: Readonly<Record<FeatureKey, FeatureDefinition>> = {
  'PLATFORM.MULTI_BRANCH': planned('PLATFORM.MULTI_BRANCH', 'Multi-branch'),
  'INVENTORY.SIMPLE_STORAGE': { ...planned('INVENTORY.SIMPLE_STORAGE', 'Simple storage'), defaultEnabled: true, status: 'ACTIVE' },
  'INVENTORY.ADVANCED_WAREHOUSE': planned('INVENTORY.ADVANCED_WAREHOUSE', 'Advanced warehouse', ['INVENTORY.LOCATION_TRACKING']),
  'INVENTORY.LOCATION_TRACKING': { ...planned('INVENTORY.LOCATION_TRACKING', 'Location tracking'), defaultEnabled: true, status: 'ACTIVE' },
  'INVENTORY.BATCH_STATUS': { ...planned('INVENTORY.BATCH_STATUS', 'Batch status tracking'), defaultEnabled: true, status: 'ACTIVE' },
  'INVENTORY.INTERNAL_TRANSFERS': { ...planned('INVENTORY.INTERNAL_TRANSFERS', 'Internal location transfers'), defaultEnabled: true, status: 'ACTIVE' },
  'INVENTORY.RESERVATIONS': planned('INVENTORY.RESERVATIONS', 'Inventory reservations'),
  'INVENTORY.BARCODE_SCANNING': planned('INVENTORY.BARCODE_SCANNING', 'Barcode scanning', ['INVENTORY.LOCATION_TRACKING']),
  'INVENTORY.PICK_LISTS': planned('INVENTORY.PICK_LISTS', 'Pick lists', ['INVENTORY.ADVANCED_WAREHOUSE']),
  'INVENTORY.DIRECTED_PUTAWAY': planned('INVENTORY.DIRECTED_PUTAWAY', 'Directed put-away', ['INVENTORY.ADVANCED_WAREHOUSE']),
  'MANUFACTURING.ENABLED': { ...planned('MANUFACTURING.ENABLED', 'Manufacturing'), defaultEnabled: true, status: 'ACTIVE' },
  'FINANCE.ENABLED': { ...planned('FINANCE.ENABLED', 'Finance'), defaultEnabled: true, status: 'ACTIVE' }, 'FINANCE.ACCOUNTS_PAYABLE': { ...planned('FINANCE.ACCOUNTS_PAYABLE', 'Accounts payable'), defaultEnabled: true, status: 'ACTIVE' }, 'FINANCE.SUPPLIER_INVOICES': { ...planned('FINANCE.SUPPLIER_INVOICES', 'Supplier invoices'), defaultEnabled: true, status: 'ACTIVE' }, 'FINANCE.SUPPLIER_PAYMENTS': { ...planned('FINANCE.SUPPLIER_PAYMENTS', 'Supplier payments'), defaultEnabled: true, status: 'ACTIVE' }, 'FINANCE.EXPENSES': { ...planned('FINANCE.EXPENSES', 'Expenses'), defaultEnabled: true, status: 'ACTIVE' }, 'FINANCE.CASH_ACCOUNTS': { ...planned('FINANCE.CASH_ACCOUNTS', 'Cash accounts'), defaultEnabled: true, status: 'ACTIVE' }, 'FINANCE.BANK_ACCOUNTS': { ...planned('FINANCE.BANK_ACCOUNTS', 'Bank accounts'), defaultEnabled: true, status: 'ACTIVE' }, 'FINANCE.PETTY_CASH': planned('FINANCE.PETTY_CASH', 'Petty cash'), 'FINANCE.APPROVALS': planned('FINANCE.APPROVALS', 'Financial approvals'), 'FINANCE.CHART_OF_ACCOUNTS': { ...planned('FINANCE.CHART_OF_ACCOUNTS', 'Chart of accounts'), defaultEnabled: true, status: 'ACTIVE' }, 'FINANCE.JOURNALS': { ...planned('FINANCE.JOURNALS', 'Journals'), defaultEnabled: true, status: 'ACTIVE' }, 'FINANCE.PERIODS': { ...planned('FINANCE.PERIODS', 'Accounting periods'), defaultEnabled: true, status: 'ACTIVE' }, 'FINANCE.POS_SETTLEMENTS': planned('FINANCE.POS_SETTLEMENTS', 'POS settlements'), 'FINANCE.BRANCH_REPORTING': planned('FINANCE.BRANCH_REPORTING', 'Branch reporting'), 'FINANCE.CONSOLIDATED_REPORTING': planned('FINANCE.CONSOLIDATED_REPORTING', 'Consolidated reporting'), 'CRM.ENABLED': planned('CRM.ENABLED', 'CRM'), 'LOYALTY.ENABLED': planned('LOYALTY.ENABLED', 'Loyalty'), 'FRANCHISE.ENABLED': planned('FRANCHISE.ENABLED', 'Franchise'),
}
export function resolveFeature(key: FeatureKey, organizationId: string, branchId: string | null, configurations: readonly FeatureConfiguration[]): boolean { const org = configurations.find((item) => item.featureKey === key && item.organizationId === organizationId && item.branchId === null); const branch = branchId === null ? undefined : configurations.find((item) => item.featureKey === key && item.organizationId === organizationId && item.branchId === branchId); return branch?.enabled ?? org?.enabled ?? FEATURE_REGISTRY[key].defaultEnabled }
export function validateFeatureConfiguration(key: FeatureKey, enabled: boolean, organizationId: string, branchId: string | null, configurations: readonly FeatureConfiguration[]): void { if (!enabled) { const dependents = (Object.keys(FEATURE_REGISTRY) as FeatureKey[]).filter((candidate) => FEATURE_REGISTRY[candidate].dependencies.includes(key) && resolveFeature(candidate, organizationId, branchId, configurations)); if (dependents.length) throw new Error(`${key} cannot be disabled while ${dependents.join(', ')} is enabled.`); return } for (const dependency of FEATURE_REGISTRY[key].dependencies) if (!resolveFeature(dependency, organizationId, branchId, configurations)) throw new Error(`${key} requires ${dependency}.`) }
